Commissioning Cluster
Files
file zcl_commissioning.c
Implementation of ZCL Commissioning Cluster.
file zcl_commissioning.h
Header for ZCL Commissioning Cluster.
Data Structures
struct zcl_comm_startup_param_t
struct zcl_comm_state_t
struct zcl_comm_startup_attr_t
Macros
#define ZCL_CLUST_COMMISSIONING 0x0015
#define ZCL_CLUST_ENTRY_COMMISSIONING_SERVER
#define ZCL_COMM_GLOBAL_EPID ZCL64_INIT(0x0050C277, 0x10000000)
#define ZCL_COMM_STARTUP_JOINED 0x00
#define ZCL_COMM_STARTUP_COORDINATOR 0x01
#define ZCL_COMM_STARTUP_REJOIN 0x02
#define ZCL_COMM_STARTUP_FROM_SCRATCH 0x03
#define ZCL_COMM_KEY_TYPE_STANDARD 0x01
#define ZCL_COMM_KEY_TYPE_HIGH_SECURITY 0x05
#define ZCL_COMM_SCAN_ATTEMPTS_DEFAULT 0x05
#define ZCL_COMM_TIME_BETWEEN_SCANS_DEFAULT 0x0064
#define ZCL_COMM_REJOIN_INTERVAL_DEFAULT 0x003c
#define ZCL_COMM_MAX_REJOIN_INTERVAL_DEFAULT 0x0e10
#define ZCL_COMM_CONCENTRATOR_RADIUS_DEFAULT 0x0F
#define ZCL_COMM_FLAG_SAVE_ON_JOIN 0x01
if radio successfully joins a network, commit changes to NVRAM
#define ZCL_COMM_FLAG_DELAYED_RESTART 0x02
there is a delayed action to perform
#define ZCL_COMM_FLAG_COORDINATOR_OK 0x04
this device can be a coordinator
#define ZCL_COMM_FLAG_ROUTER_OK 0x08
this device can be a router
#define ZCL_COMM_FLAG_ENDDEV_OK 0x10
this device can be a end device
#define ZCL_COMM_FLAG_FACTORY_RESET 0x40
reset to factory SAS at the delayed restart
#define ZCL_COMM_FLAG_INSTALL 0x80
install the current SAS at the delayed restart
#define ZCL_COMM_STATE_INIT 0x00
startup state
#define ZCL_COMM_STATE_LOADING 0x01
loading structure
#define ZCL_COMM_STATE_STARTUP 0x02
xbee_commissioning_tick() can process startup_control
#define ZCL_COMM_STATE_UNJOINED 0x03
radio is not joined to a network
#define ZCL_COMM_STATE_REFRESH 0x04
radio has joined a network and we're refreshing the structure
#define ZCL_COMM_STATE_JOINED 0x05
radio is joined to a network
#define ZCL_COMM_ATTR_SHORT_ADDRESS 0x0000
#define ZCL_COMM_ATTR_EXTENDED_PANID 0x0001
#define ZCL_COMM_ATTR_PANID 0x0002
#define ZCL_COMM_ATTR_CHANNEL_MASK 0x0003
#define ZCL_COMM_ATTR_PROTOCOL_VERSION 0x0004
#define ZCL_COMM_ATTR_STACK_PROFILE 0x0005
#define ZCL_COMM_ATTR_STARTUP_CONTROL 0x0006
#define ZCL_COMM_ATTR_TRUST_CTR_ADDR 0x0010
#define ZCL_COMM_ATTR_TRUST_CTR_MASTER_KEY 0x0011
#define ZCL_COMM_ATTR_NETWORK_KEY 0x0012
#define ZCL_COMM_ATTR_USE_INSECURE_JOIN 0x0013
#define ZCL_COMM_ATTR_PRECONFIG_LINK_KEY 0x0014
#define ZCL_COMM_ATTR_NETWORK_KEY_SEQ_NUM 0x0015
#define ZCL_COMM_ATTR_NETWORK_KEY_TYPE 0x0016
#define ZCL_COMM_ATTR_NETWORK_MGR_ADDR 0x0017
#define ZCL_COMM_ATTR_SCAN_ATTEMPTS 0x0020
#define ZCL_COMM_ATTR_TIME_BTWN_SCANS 0x0021
#define ZCL_COMM_ATTR_REJOIN_INTERVAL 0x0022
#define ZCL_COMM_ATTR_MAX_REJOIN_INTERVAL 0x0023
#define ZCL_COMM_ATTR_INDIRECT_POLL_RATE 0x0030
#define ZCL_COMM_ATTR_PARENT_RETRY_THRESHOLD 0x0031
#define ZCL_COMM_ATTR_CONCENTRATOR_FLAG 0x0040
#define ZCL_COMM_ATTR_CONCENTRATOR_RADIUS 0x0041
#define ZCL_COMM_ATTR_CONCENTRATOR_DISC_TIME 0x0042
#define ZCL_COMM_CMD_RESTART_DEVICE 0x00
#define ZCL_COMM_RESTART_OPT_MODE_MASK 0x07
#define ZCL_COMM_RESTART_OPT_MODE_SAVE_CHANGES 0x00
#define ZCL_COMM_RESTART_OPT_MODE_NO_CHANGES 0x01
#define ZCL_COMM_RESTART_OPT_IMMEDIATE 0x08
#define ZCL_COMM_RESTART_OPT_RESERVED_MASK 0xF0
#define ZCL_COMM_CMD_SAVE_STARTUP_PARAM 0x01
#define ZCL_COMM_CMD_RESTORE_STARTUP_PARAM 0x02
#define ZCL_COMM_CMD_RESET_STARTUP_PARAM 0x03
#define ZCL_COMM_RESET_OPT_CURRENT 0x01
#define ZCL_COMM_RESET_OPT_ALL 0x02
#define ZCL_COMM_RESET_OPT_ERASE_INDEX 0x04
#define ZCL_COMM_CMD_RESTART_DEVICE_RESP 0x00
#define ZCL_COMM_CMD_SAVE_STARTUP_PARAM_RESP 0x01
#define ZCL_COMM_CMD_RESTORE_STARTUP_PARAM_RESP 0x02
#define ZCL_COMM_CMD_RESET_STARTUP_PARAM_RESP 0x03
Typedefs
typedef PACKED_STRUCT zcl_comm_restart_device_cmd_t
typedef PACKED_STRUCT zcl_comm_save_startup_param_t
typedef PACKED_STRUCT zcl_comm_restore_startup_param_t
typedef PACKED_STRUCT zcl_comm_reset_startup_param_t
Functions
int _zcl_comm_startup_control_set (const zcl_attribute_full_t FAR *attribute, zcl_attribute_write_rec_t *rec)
Limit values of startup_control based on firmware type (e.g., some firmwares can't be ZCL_COMM_STARTUP_COORDINATOR).
int zcl_comm_response (const wpan_envelope_t FAR *envelope, uint_fast8_t status)
Send response to a Commissioning Server Cluster request.
int _zcl_comm_command_build (wpan_envelope_t FAR *envelope, zcl_header_nomfg_t *header)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
int _zcl_comm_command_send (wpan_envelope_t FAR *envelope)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
int zcl_comm_restart_device (wpan_envelope_t FAR *envelope, const zcl_comm_restart_device_cmd_t *parameters)
Send a `Restart Device` command to the ZCL Commissioning Cluster.
int zcl_comm_reset_parameters (wpan_envelope_t FAR *envelope, const zcl_comm_reset_startup_param_t *parameters)
Send a `Reset Startup Parameters` command to the ZCL Commissioning Cluster.
int rand_range (int range)
bool_t zcl_comm_sas_is_valid (const zcl_comm_state_t FAR *comm)
Partial implementation of a function to validate a Startup Attribute Set before trying to use it.
int zcl_comm_clust_handler (const wpan_envelope_t FAR *envelope, void FAR *context)
void zcl_comm_sas_init (zcl_comm_startup_param_t *p)
void zcl_comm_factory_reset (uint16_t ms_delay)
Perform a locally-triggered factory reset to default SAS.
Variables
const zcl64_t zcl_comm_global_epid = ZCL_COMM_GLOBAL_EPID
zcl_comm_state_t zcl_comm_state = { { 0 } }
const zcl_comm_startup_attr_t zcl_comm_startup_attributes
const zcl_attribute_tree_t zcl_comm_startup_attribute_tree []
const zcl64_t zcl_comm_global_epid
uint16_t short_address
zcl64_t extended_panid
uint16_t panid
uint32_t channel_mask
uint8_t startup_control
uint8_t network_key_le [16]
bool_t use_insecure_join
uint8_t preconfig_link_key_le [16]
uint8_t network_key_seq_num
uint8_t network_key_type
uint16_t network_mgr_addr
uint8_t scan_attempts
uint16_t time_between_scans
uint16_t rejoin_interval
uint16_t max_rejoin_interval
bool_t flag
uint8_t radius
uint8_t discovery_time
xx xx xx xx xx xx xx xx xx
struct {
 bool_t flag
 uint8_t radius
 uint8_t discovery_time
} concentrator
zcl_comm_startup_param_t sas
uint8_t flags
uint32_t restart_ms
value of xbee_millisecond_timer() when it's time to restart
uint8_t state
zcl_attribute_base_t short_address
zcl_attribute_base_t extended_panid
zcl_attribute_base_t panid
zcl_attribute_base_t channel_mask
zcl_attribute_full_t startup_control
zcl_attribute_base_t trust_ctr_addr
zcl_attribute_base_t trust_ctr_master_key
zcl_attribute_base_t network_key
zcl_attribute_base_t use_insecure_join
zcl_attribute_base_t preconfig_link_key
zcl_attribute_base_t network_key_seq_num
zcl_attribute_base_t network_key_type
zcl_attribute_base_t network_mgr_addr
zcl_attribute_full_t scan_attempts
zcl_attribute_full_t time_between_scans
zcl_attribute_full_t rejoin_interval
zcl_attribute_full_t max_rejoin_interval
zcl_attribute_base_t flag
zcl_attribute_base_t radius
zcl_attribute_base_t discovery_time
xx xx xx xx xx xx xx xx xx
struct {
 zcl_attribute_base_t flag
 zcl_attribute_base_t radius
 zcl_attribute_base_t discovery_time
} concentrator
uint16_t end_of_list
zcl_comm_state_t zcl_comm_state
const zcl_comm_startup_param_t zcl_comm_default_sas
const zcl_comm_startup_attr_t zcl_comm_startup_attributes
const zcl_attribute_tree_t zcl_comm_startup_attribute_tree []
uint8_t delay
uint8_t jitter
uint8_t index
Detailed Description
Macro Definition Documentation
#define ZCL_CLUST_ENTRY_COMMISSIONING_SERVER
Value:
{ ZCL_CLUST_COMMISSIONING, &zcl_comm_clust_handler, \
      zcl_comm_startup_attribute_tree, WPAN_CLUST_FLAG_SERVER
       }
Typedef Documentation
zcl_comm_reset_startup_param_t
Initial value:
{
   uint8_t options
zcl_comm_restart_device_cmd_t
Initial value:
{
   uint8_t options
zcl_comm_restore_startup_param_t
Initial value:
{
   uint8_t options
zcl_comm_save_startup_param_t
Initial value:
{
   uint8_t options
Function Documentation
int _zcl_comm_command_build (wpan_envelope_t FAR * envelope, zcl_header_nomfg_t * header)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
Fills in frame_control and sequence of header. Fills in cluster_id and payload of envelope. Fills in source_endpoint and profile_id of envelope if necessary.
Caller needs to fill in envelope->length and header->command
References EINVAL, wpan_endpoint_table_entry_t::endpoint, wpan_endpoint_table_entry_t::profile_id, WPAN_CLUST_FLAG_CLIENT, wpan_endpoint_next_trans(), wpan_endpoint_of_cluster(), wpan_endpoint_of_envelope(), ZCL_FRAME_CLIENT_TO_SERVER, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_GENERAL, and ZCL_FRAME_TYPE_CLUSTER.
Referenced by zcl_comm_reset_parameters(), and zcl_comm_restart_device().
int _zcl_comm_command_send (wpan_envelope_t FAR * envelope)
Common function used by zcl_comm_restart_device and zcl_comm_reset_parameters.
sends the envelope and then resets the payload and length before returning
References wpan_envelope_send().
Referenced by zcl_comm_reset_parameters(), and zcl_comm_restart_device().
int _zcl_comm_startup_control_set (const zcl_attribute_full_t FAR * attribute, zcl_attribute_write_rec_t * rec)
Limit values of startup_control based on firmware type (e.g., some firmwares can't be ZCL_COMM_STARTUP_COORDINATOR).
Parameters
in attribute should be a pointer to zcl_comm_startup_attributes.startup_control
in,out rec value from write request
See zcl_attribute_write_fn() for calling convention.
References zcl_attribute_write_rec_t::buffer, zcl_attribute_write_rec_t::flags, zcl_attribute_write_rec_t::status, value, ZCL_ATTR_WRITE_FLAG_ASSIGN, ZCL_COMM_FLAG_COORDINATOR_OK, ZCL_COMM_FLAG_ENDDEV_OK, and ZCL_COMM_FLAG_ROUTER_OK.
void zcl_comm_factory_reset (uint16_t ms_delay)
Perform a locally-triggered factory reset to default SAS.
Parameters
in ms_delay initiate reset after ms_delay milliseconds
References zcl_comm_state_t::restart_ms, ZCL_COMM_FLAG_DELAYED_RESTART, ZCL_COMM_FLAG_FACTORY_RESET, and ZCL_COMM_FLAG_INSTALL.
int zcl_comm_reset_parameters (wpan_envelope_t FAR * envelope, const zcl_comm_reset_startup_param_t * parameters)
Send a `Reset Startup Parameters` command to the ZCL Commissioning Cluster.
Parameters
in,out envelope Partial envelope used to send the request. Caller must set dev, ieee_address, network_address, profile_id, source_endpoint, dest_endpoint and (optionally) options. On return, payload and length are cleared, and cluster_id is set to ZCL_CLUST_COMMISSIONING.
If source_endpoint is 0, function will search the endpoint table for a Commissioning Client Cluster and set the envelope's source_endpoint and profile_id.
Parameters
in parameters Parameters for the Reset Startup Parameters command or NULL for default settings (reset current parameters only).
Return values
0 request sent
-EINVAL couldn't find source endpoint in endpoint table, or some other error in parameter passed to function
!0 error trying to send request
References _zcl_comm_command_build(), _zcl_comm_command_send(), and PACKED_STRUCT.
int zcl_comm_restart_device (wpan_envelope_t FAR * envelope, const zcl_comm_restart_device_cmd_t * parameters)
Send a `Restart Device` command to the ZCL Commissioning Cluster.
Parameters
in,out envelope Partial envelope used to send the request. Caller must set dev, ieee_address, network_address, profile_id, source_endpoint, dest_endpoint and (optionally) options. On return, payload and length are cleared, and cluster_id is set to ZCL_CLUST_COMMISSIONING.
If source_endpoint is 0, function will search the endpoint table for a Commissioning Client Cluster and set the envelope's source_endpoint and profile_id.
Parameters
in parameters Parameters for the Restart Device command or NULL for default settings (save changes and restart without delay/jitter).
Return values
0 request sent
-EINVAL couldn't find source endpoint in endpoint table, or some other error in parameter passed to function
!0 error trying to send request
References _zcl_comm_command_build(), _zcl_comm_command_send(), and PACKED_STRUCT.
bool_t zcl_comm_sas_is_valid (const zcl_comm_state_t FAR * comm)
Partial implementation of a function to validate a Startup Attribute Set before trying to use it.
Parameters
in comm Startup Attribute Set to test.
Return values
TRUE Startup Attribute Set is valid
FALSE Startup Attribute Set is invalid and cannot be used
Todo
Todo add more tests to this function
References memcheck(), and WPAN_NET_ADDR_COORDINATOR.
Variable Documentation
const zcl_attribute_tree_t zcl_comm_startup_attribute_tree[]
Initial value:
=
      { { ZCL_MFG_NONE, &zcl_comm_startup_attributes.short_address, NULL } }