ZigBee Cluster Library
Modules
64-bit integer support
Datatypes
Cluster Client support code
Clusters
Files
file zigbee_zcl.c
Process General Commands for ZigBee Cluster Library and provide support functions to other layers of the stack.
file zcl.h
Header for implementation of ZigBee Cluster Library.
Data Structures
union zcl_rec_reporting_config_t
union zcl_attribute_minmax_t
struct zcl_attribute_write_rec_t
struct zcl_attribute_base_t
Basic structure for storing a list of attributes in a cluster.
struct zcl_attribute_full_t
Use this structure for attributes with min/max values or the need to have a read/write function.
struct zcl_array_t
If a zcl_attribute_base_t has a type of ZCL_TYPE_ARRAY, its .value points to this structure.
struct zcl_struct_element_t
A zcl_struct_t contains an array of these elements, describing each element in the structure and its offset from the zcl_struct_t.base_address.
struct zcl_struct_t
If a zcl_attribute_base_t has a type of ZCL_TYPE_STRUCT, its .value points to this structure.
struct zcl_attribute_tree_t
struct zcl_command_t
Structure populated by zcl_command_build() with the ZCL header from a received ZCL command frame.
Macros
#define zigbee_zcl_debug
#define ZCL_DISCOVER_ATTRIB_MAX 20
#define ZCL_CMD_MATCH(p, mfg, dir, type)
Macro for checking the frame control field of a ZCL command.
#define ZCL_CMD_IS_PROFILE(p) (ZCL_FRAME_TYPE_PROFILE == ((const uint8_t FAR *)(p) & ZCL_FRAME_TYPE_MASK))
Identify profile commands (as opposed to cluster commands) using the frame control field of a ZCL command.
#define ZCL_CMD_IS_MFG_CLUSTER(p)
Identify manufacturer-specific cluster commands using the frame control field of a ZCL command.
#define ZCL_CMD_IS_CLUSTER(p)
Identify cluster commands that are not manufacturer-specific, using the frame control field of a ZCL command.
#define ZCL_DIRECTION_SEND 0x00
#define ZCL_DIRECTION_RECEIVE 0x01
#define ZCL_INDICATOR_INDICES_MASK 0x0F
#define ZCL_INDICATOR_ACTION_MASK 0xF0
#define ZCL_INDICATOR_REPLACE 0x00
#define ZCL_INDICATOR_ADD_ELEMENT 0x10
#define ZCL_INDICATOR_REMOVE_ELEMENT 0x20
#define ZCL_ATTR_WRITE_FLAG_NONE 0x00
#define ZCL_ATTR_WRITE_FLAG_ASSIGN 0x01
Assign the new value to the attribute (if not set, just checks the validity of the data).
#define ZCL_ATTR_WRITE_FLAG_WRITE_REQ 0x00
Parsing a Write Attribute Request record.
#define ZCL_ATTR_WRITE_FLAG_READ_RESP 0x02
Parsing a Read Attribute Response record.
#define ZCL_ATTRIBUTE_END_OF_LIST 0xFFFF
Attribute ID for end of list marker.
#define ZCL_MFG_NONE 0x0000
Typedefs
typedef PACKED_STRUCT zcl_header_common_t
Common portion of ZCL header (appears after optional Manufacturer Code)
typedef PACKED_STRUCT zcl_header_t
General header for casting onto an incoming frame.
typedef PACKED_STRUCT zcl_header_response_t
ZCL header structure used for building response frames that may or may not be manufacturer-specific.
typedef PACKED_STRUCT zcl_header_withmfg_t
ZLC header structure used when building a manufacturer-specific response frame.
typedef PACKED_STRUCT zcl_header_nomfg_t
ZLC header structure used when building a normal (non-manufacturer-specific response frame.
typedef PACKED_STRUCT zcl_attrib_t
General format for an attribute, used for Write Attributes and Report Attributes commands.
typedef PACKED_STRUCT zcl_rec_read_attrib_resp_t
Used for ZCL_CMD_READ_ATTRIB_RESP.
typedef PACKED_STRUCT zcl_rec_read_attrib_error_resp_t
typedef PACKED_STRUCT zcl_rec_read_attrib_array_resp_t
typedef PACKED_STRUCT zcl_rec_read_attrib_struct_resp_t
typedef PACKED_STRUCT zcl_rec_write_attrib_status_t
Used for ZCL_CMD_WRITE_ATTRIB_RESP.
typedef PACKED_STRUCT zcl_rec_report_send_t
typedef PACKED_STRUCT zcl_rec_report_receive_t
typedef PACKED_STRUCT zcl_rec_reporting_status_t
typedef PACKED_STRUCT zcl_rec_read_report_cfg_t
typedef PACKED_STRUCT zcl_rec_report_error_resp_t
typedef PACKED_STRUCT zcl_rec_report_send_resp_t
typedef PACKED_STRUCT zcl_rec_report_receive_resp_t
typedef PACKED_STRUCT zcl_default_response_t
Used for ZCL_CMD_DEFAULT_RESP.
typedef PACKED_STRUCT zcl_discover_attrib_t
Used for ZCL_CMD_DISCOVER_ATTRIB.
typedef PACKED_STRUCT zcl_rec_attrib_report_t
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
typedef PACKED_STRUCT zcl_discover_attrib_resp_t
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
typedef PACKED_STRUCT zcl_selector_t
typedef PACKED_STRUCT zcl_read_struct_attrib_t
typedef PACKED_STRUCT zcl_rec_write_struct_attrib_t
typedef PACKED_STRUCT zcl_rec_write_struct_attrib_resp_t
typedef uint_fast8_t(* zcl_attribute_update_fn)(const struct zcl_attribute_full_t FAR *entry)
Function pointer assigned to a ZCL attribute record, called to update the value of the given attribute.
typedef int(* zcl_attribute_write_fn)(const struct zcl_attribute_full_t FAR *entry, zcl_attribute_write_rec_t *rec)
Function pointer assigned to a ZCL attribute record, called instead of zcl_decode_attribute() to process a Write Request for the attribute.
Functions
zigbee_zcl_debug int zcl_send_response (zcl_command_t *request, const void FAR *response, uint16_t length)
Send a response to a ZCL command.
zigbee_zcl_debug const
*
zcl_attribute_base_t FAR * zcl_attribute_get_next (const zcl_attribute_base_t FAR *entry)
Return a pointer to the next attribute entry from an attribute table.
zigbee_zcl_debug const
*
zcl_attribute_base_t FAR * zcl_find_attribute (const zcl_attribute_base_t FAR *entry, uint16_t search_id)
Search the attribute table starting at entry, for attribute ID search_id.
zigbee_zcl_debug int zcl_build_header (zcl_header_response_t *rsp, zcl_command_t *cmd)
Support function to fill in a ZCL response header.
zigbee_zcl_debug int zcl_default_response (zcl_command_t *request, uint8_t status)
Send a Default Response (ZCL_CMD_DEFAULT_RESP) to a given command.
zigbee_zcl_debug int zcl_check_minmax (const zcl_attribute_base_t FAR *entry, const uint8_t FAR *buffer_le)
Checks whether a new value from a Write Attributes command is within the limits specified for a given attribute.
zigbee_zcl_debug int zcl_parse_attribute_record (const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *write_rec)
Parse an attribute record from a Write Attributes Request or a Read Attributes Response and possibly store the new attribute value.
zigbee_zcl_debug uint32_t zcl_convert_24bit (const void FAR *value_le, bool_t extend_sign)
Convert a 24-bit (3-byte) little-endian value to a 32-bit value in host byte order.
zigbee_zcl_debug int zcl_decode_attribute (const zcl_attribute_base_t FAR *entry, zcl_attribute_write_rec_t *rec)
Decode attribute value from a Write Attribute Request or Read Attribute Response record and optionally write to entry.
int _zcl_write_attributes (zcl_command_t *cmd)
Process the three types of Write Attributes requests.
zigbee_zcl_debug int _zcl_encode_struct_value (uint8_t FAR *buffer, int16_t bufsize, const zcl_struct_t FAR *zcl_struct)
Format a ZCL struct for a Read Attributes Response or a Write Attributes Request.
zigbee_zcl_debug int _zcl_encode_array_value (uint8_t FAR *buffer, int16_t bufsize, const zcl_array_t FAR *array)
Format a ZCL array for a Read Attributes Response or a Write Attributes Request.
zigbee_zcl_debug int zcl_encode_attribute_value (uint8_t FAR *buffer, int16_t bufsize, const zcl_attribute_base_t FAR *entry)
Format a ZCL attribute's value for a Read Attributes Response or a Write Attributes Request.
int _zcl_read_attributes (zcl_command_t *cmd)
Process the Read Attributes Command (ZCL_CMD_READ_ATTRIB).
int _zcl_discover_attributes (zcl_command_t *cmd)
Process the Discover Attributes Command (ZCL_CMD_DISCOVER_ATTRIB).
zigbee_zcl_debug int zcl_command_build (zcl_command_t *cmd, const wpan_envelope_t FAR *envelope, zcl_attribute_tree_t FAR *tree)
Parse a ZCL request and store in a zcl_command_t structure with fields in fixed locations (therefore easier to use than the variable-length frame header).
zigbee_zcl_debug void zcl_command_dump (const zcl_command_t *cmd)
Debugging routine that dumps contents of a parsed ZCL command structure to STDOUT.
void zcl_envelope_payload_dump (const wpan_envelope_t *envelope)
Debugging routine that parses an envelope payload as a ZCL command and dumps a parsed copy to STDOUT.
zigbee_zcl_debug int zcl_invalid_cluster (const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
Called if a request comes in for an invalid endpoint/cluster combination.
zigbee_zcl_debug int zcl_invalid_command (const wpan_envelope_t FAR *envelope)
Called if a request comes in for an invalid command on a valid endpoint/cluster combination.
zigbee_zcl_debug int zcl_general_command (const wpan_envelope_t FAR *envelope, void FAR *context)
Handler for ZCL General Commands.
zigbee_zcl_debug const char * zcl_status_text (uint_fast8_t status)
Converts a ZCL status byte (one of the ZCL_STATUS_* macros) into a string.
Variables
const zcl_attribute_tree_t FAR zcl_attributes_none [1]
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
uint8_t command
uint8_t payload [1]
first byte of variable-length field
PACKED_STRUCT
zcl_header_common_t common
mfg
manufacturer-specific extension
std
standard
xx xx xx xx xx xx xx xx xx
union {
 PACKED_STRUCT
 zcl_header_common_t common
 mfg
  manufacturer-specific extension
 std
  standard
} type
see zigbee/zcl_types.h
uint8_t sequence
uint16_t mfg_code_le
uint8_t value [1]
variable length, depending on type
uint8_t status
uint8_t element_type
uint16_t count_le
number of elements to follow
uint8_t elements [1]
mult. uint8_t type and variable-length value
uint16_t id_le
uint16_t attrib_id_le
uint8_t attrib_type
uint16_t min_interval_le
uint16_t max_interval_le
uint16_t timeout_period_le
PACKED_STRUCT
uint16_t attrib_id_le
common
zcl_rec_report_send_t send
zcl_rec_report_receive_t receive
uint8_t direction
zcl_rec_report_send_t report_cfg
uint8_t max_return_count
zcl_rec_attrib_report_t attrib [1]
uint16_t index_le [15]
zcl_selector_t selector
uint16_t id
int32_t _signed
uint32_t _unsigned
float _float
const uint8_t FAR * buffer
Source data to write to attribute.
int16_t buflen
Number of bytes in buffer.
uint8_t flags
Parsing flags (see ZCL_ATTR_WRITE_FLAG_* macros for valid flags).
uint8_t status
Set to #ZCL_STATUS_SUCCESS if data is valid, or some other ZCL_STATUS_* macro if there's an error.
uint16_t id
uint8_t flags
uint8_t type
The ZCL Attribute Type, should be one of the ZCL_TYPE_* macros defined in zigbee/zcl_types.h.
const void FAR * value
Pointer to global variable of correct type, set as const to allow for both const and non-const values.
zcl_attribute_base_t base
zcl_attribute_minmax_t min
Minimum value for attribute (currently unused until I pick a value to represent `none`).
zcl_attribute_minmax_t max
Maximum value for attribute, assumes 32-bit limit.
zcl_attribute_update_fn read
On an attribute read, the ZCL dispatcher will call the .read function to refresh the attribute's value before responding to the request.
zcl_attribute_write_fn write
On an attribute write, the ZCL dispatcher will call the .write function with a structure containing information about the write request.
uint16_t max_count
maximum number of elements to store
uint16_t current_count
current number of elements
uint16_t element_size
number of bytes in each element
uint8_t type
type of data stored in array
const void FAR * value
uint8_t zcl_type
ZCL data type of element.
uint16_t offset
offset into structure
uint16_t element_count
number of elements in structure
const void FAR * base_address
base address of structure
const zcl_struct_element_t FAR * element
elements in the structure
uint16_t manufacturer_id
ID for manufacturer-specific attributes or ZCL_MFG_NONE if general.
const zcl_attribute_base_t FAR * server
List of attributes for the SERVER cluster (or NULL if none).
const zcl_attribute_base_t FAR * client
List of attributes for the CLIENT cluster (or NULL if none).
const zcl_attribute_tree_t FAR zcl_attributes_none [1]
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
const wpan_envelope_t FAR * envelope
envelope for the received command, envelope's payload and length include the ZCL header
uint8_t frame_control
frame control byte from the ZCL header
uint16_t mfg_code
manufacturer code from the ZCL header, in host byte order, or 0x0000 if not mfg specific
uint8_t sequence
sequence byte from the ZCL header
uint8_t command
command byte from the ZCL header
const zcl_attribute_base_t FAR * attributes
Appropriate list of attributes on this device, related to the command.
const void FAR * zcl_payload
pointer to the ZCL payload (first byte after ZCL header)
int16_t length
length of the ZCL payload
0x0000-0x00ff General Clusters
#define ZCL_CLUST_BASIC 0x0000
#define ZCL_CLUST_POWER_CONFIG 0x0001
#define ZCL_CLUST_DEVICE_TEMP_CONFIG 0x0002
#define ZCL_CLUST_IDENTIFY 0x0003
#define ZCL_CLUST_GROUPS 0x0004
#define ZCL_CLUST_SCENES 0x0005
#define ZCL_CLUST_ONOFF 0x0006
#define ZCL_CLUST_ONOFF_SWITCH_CONFIG 0x0007
#define ZCL_CLUST_LEVEL_CONTROL 0x0008
#define ZCL_CLUST_ALARMS 0x0009
#define ZCL_CLUST_TIME 0x000a
#define ZCL_CLUST_RSSI_LOCATION 0x000b
#define ZCL_CLUST_ANALOG_IN 0x000c
#define ZCL_CLUST_ANALOG_OUT 0x000d
#define ZCL_CLUST_ANALOG_VALUE 0x000e
#define ZCL_CLUST_BINARY_IN 0x000f
#define ZCL_CLUST_BINARY_OUT 0x0010
#define ZCL_CLUST_BINARY_VALUE 0x0011
#define ZCL_CLUST_MULTI_IN 0x0012
#define ZCL_CLUST_MULTI_OUT 0x0013
#define ZCL_CLUST_MULTI_VALUE 0x0014
#define ZCL_CLUST_COMMISSIONING 0x0015
0x0100-0x01ff Closure Clusters
#define ZCL_CLUST_SHADE_CONFIG 0x0100
0x0200-0x02ff HVAC Clusters
#define ZCL_CLUST_PUMP_CONFIG 0x0200
#define ZCL_CLUST_THERMOSTAT 0x0201
#define ZCL_CLUST_FAN_CONTROL 0x0202
#define ZCL_CLUST_DEHUMIDIFY_CONTROL 0x0203
#define ZCL_CLUST_THERMOSTAT_UI_CONFIG 0x0204
0x0300-0x03ff Lighting Clusters
#define ZCL_CLUST_COLOR_CONTROL 0x0300
#define ZCL_CLUST_BALLAST_CONFIG 0x0301
0x0400-0x04ff Measurement and Sensing Clusters
#define ZCL_CLUST_ILLUM_MEASURE 0x0400
#define ZCL_CLUST_ILLUM_LEVEL_SENSING 0x0401
#define ZCL_CLUST_TEMP_MEASURE 0x0402
#define ZCL_CLUST_PRESSURE_MEASURE 0x0403
#define ZCL_CLUST_FLOW_MEASURE 0x0404
#define ZCL_CLUST_HUMIDITY_MEASURE 0x0405
#define ZCL_CLUST_OCCUPANCY_SENSING 0x0406
0x0500-0x05ff Security and Safety Clusters
#define ZCL_CLUST_IAS_ZONE 0x0500
#define ZCL_CLUST_IAS_ACE 0x0501
#define ZCL_CLUST_IAS_WD 0x0502
0x0600-0x06ff Protocol Interface Clusters
#define ZCL_CLUST_GENERIC_TUNNEL 0x0600
#define ZCL_CLUST_BACNET_TUNNEL 0x0601
#define ZCL_CLUST_BACNET_REG_ANALOG_IN 0x0602
#define ZCL_CLUST_BACNET_EXT_ANALOG_IN 0x0603
#define ZCL_CLUST_BACNET_REG_ANALOG_OUT 0x0604
#define ZCL_CLUST_BACNET_EXT_ANALOG_OUT 0x0605
#define ZCL_CLUST_BACNET_REG_ANALOG_VALUE 0x0606
#define ZCL_CLUST_BACNET_EXT_ANALOG_VALUE 0x0607
#define ZCL_CLUST_BACNET_REG_BINARY_IN 0x0608
#define ZCL_CLUST_BACNET_EXT_BINARY_IN 0x0609
#define ZCL_CLUST_BACNET_REG_BINARY_OUT 0x060a
#define ZCL_CLUST_BACNET_EXT_BINARY_OUT 0x060b
#define ZCL_CLUST_BACNET_REG_BINARY_VALUE 0x060c
#define ZCL_CLUST_BACNET_EXT_BINARY_VALUE 0x060d
#define ZCL_CLUST_BACNET_REG_MULTI_IN 0x060e
#define ZCL_CLUST_BACNET_EXT_MULTI_IN 0x060f
#define ZCL_CLUST_BACNET_REG_MULTI_OUT 0x0610
#define ZCL_CLUST_BACNET_EXT_MULTI_OUT 0x0611
#define ZCL_CLUST_BACNET_REG_MULTI_VALUE 0x0612
#define ZCL_CLUST_BACNET_EXT_MULTI_VALUE 0x0613
Bit masks for the frame_control field of a ZCL header (zcl_header_t, zcl_header_response_t, zcl_header_withmfg_t, or zcl_header_nomfg_t)
#define ZCL_FRAME_TYPE_MASK 0x03
Bits of frame type.
#define ZCL_FRAME_TYPE_PROFILE 0x00
cmd acts across entire profile
#define ZCL_FRAME_TYPE_CLUSTER 0x01
cmd is specific to a cluster
#define ZCL_FRAME_TYPE_RESERVED1 0x02
#define ZCL_FRAME_TYPE_RESERVED2 0x03
#define ZCL_FRAME_GENERAL 0x00
mfg code field not present
#define ZCL_FRAME_MFG_SPECIFIC 0x04
mfg code field present
#define ZCL_FRAME_DIRECTION 0x08
direction bit
#define ZCL_FRAME_CLIENT_TO_SERVER 0
cmd sent from client to server
#define ZCL_FRAME_SERVER_TO_CLIENT ZCL_FRAME_DIRECTION
cmd sent from server to client
#define ZCL_FRAME_DISABLE_DEF_RESP 0x10
default response only on error
#define ZCL_FRAME_RESERVED_BITS 0xE0
should be set to 0
ZCL Status Enumerations
Note that these defines use the exact names from the ZCL standard, with ZCL_STATUS_ prepended.
#define ZCL_STATUS_SUCCESS 0x00
#define ZCL_STATUS_FAILURE 0x01
#define ZCL_STATUS_NOT_AUTHORIZED 0x7e
#define ZCL_STATUS_RESERVED_FIELD_NOT_ZERO 0x7f
#define ZCL_STATUS_MALFORMED_COMMAND 0x80
#define ZCL_STATUS_UNSUP_CLUSTER_COMMAND 0x81
#define ZCL_STATUS_UNSUP_GENERAL_COMMAND 0x82
#define ZCL_STATUS_UNSUP_MANUF_CLUSTER_COMMAND 0x83
#define ZCL_STATUS_UNSUP_MANUF_GENERAL_COMMAND 0x84
#define ZCL_STATUS_INVALID_FIELD 0x85
#define ZCL_STATUS_UNSUPPORTED_ATTRIBUTE 0x86
#define ZCL_STATUS_INVALID_VALUE 0x87
#define ZCL_STATUS_READ_ONLY 0x88
#define ZCL_STATUS_INSUFFICIENT_SPACE 0x89
#define ZCL_STATUS_DUPLICATE_EXISTS 0x8a
#define ZCL_STATUS_NOT_FOUND 0x8b
#define ZCL_STATUS_UNREPORTABLE_ATTRIBUTE 0x8c
#define ZCL_STATUS_INVALID_DATA_TYPE 0x8d
#define ZCL_STATUS_INVALID_SELECTOR 0x8e
#define ZCL_STATUS_WRITE_ONLY 0x8f
#define ZCL_STATUS_INCONSISTENT_STARTUP_STATE 0x90
#define ZCL_STATUS_DEFINED_OUT_OF_BAND 0x91
#define ZCL_STATUS_HARDWARE_FAILURE 0xc0
#define ZCL_STATUS_SOFTWARE_FAILURE 0xc1
#define ZCL_STATUS_CALIBRATION_ERROR 0xc2
ZCL General Command IDs
Used for the .command element of the ZCL header.
Command IDs 0x11 to 0x7F (Standard ZigBee command) and 0x80 to 0xFF are reserved.
Note
Only supported commands are currently documented.
#define ZCL_CMD_READ_ATTRIB 0x00
Read Attributes Command, payload is 1 to n 2-byte attribute IDs.
#define ZCL_CMD_READ_ATTRIB_RESP 0x01
Read Attributes Response Command, payload is 1 to n variable-length Read Attribute Status records (zcl_rec_read_attrib_status_t).
#define ZCL_CMD_WRITE_ATTRIB 0x02
Write Attributes Command, payload is 1 to n variable-length Write Attribute Record fields (same as zcl_attrib_t).
#define ZCL_CMD_WRITE_ATTRIB_UNDIV 0x03
Write Attributes Undivided Command, same payload as Write Attributes Command (zcl_attrib_t), but attributes are only written if all attributes can be written successfully.
#define ZCL_CMD_WRITE_ATTRIB_RESP 0x04
Write Attributes Response Command, payload is a single byte (ZCL_STATUS_SUCCESS) if all writes were successful or 1 to n 3-byte Write Attribute Status records (zcl_rec_write_attrib_status_t) for each write that failed.
#define ZCL_CMD_WRITE_ATTRIB_NORESP 0x05
Write Attributes No Response Command, same payload as Write Attributes Command (ZCL_CMD_WRITE_ATTRIB), handled as a Write Attributes Command except the response is not sent.
#define ZCL_CMD_CONFIGURE_REPORT 0x06
#define ZCL_CMD_CONFIGURE_REPORT_RESP 0x07
#define ZCL_CMD_READ_REPORT_CFG 0x08
#define ZCL_CMD_READ_REPORT_CFG_RESP 0x09
#define ZCL_CMD_REPORT_ATTRIB 0x0a
#define ZCL_CMD_DEFAULT_RESP 0x0b
Default Response Command, payload is 2 bytes; Command ID and Status Code (zcl_default_response_t).
#define ZCL_CMD_DISCOVER_ATTRIB 0x0c
Discover Attributes Command, payload is 3 bytes; start attribute ID and maximum number of attributes to return (zcl_discover_attrib_t).
#define ZCL_CMD_DISCOVER_ATTRIB_RESP 0x0d
Discover Attributes Response Command payload is a `discovery complete` byte (done = ZCL_BOOL_TRUE, more attributes = ZCL_BOOL_TRUE), followed by 1 to n 3-byte Attribute Report fields (zcl_rec_attrib_report_t).
#define ZCL_CMD_READ_STRUCT_ATTRIB 0x0e
#define ZCL_CMD_WRITE_STRUCT_ATTRIB 0x0f
#define ZCL_CMD_WRITE_STRUCT_ATTRIB_RESP 0x10
Values for flags element of zcl_attribute_base_t.
#define ZCL_ATTRIB_FLAG_NONE 0x00
#define ZCL_ATTRIB_FLAG_WRITEONLY 0x01
#define ZCL_ATTRIB_FLAG_READONLY 0x02
#define ZCL_ATTRIB_FLAG_HAS_MIN 0x04
#define ZCL_ATTRIB_FLAG_HAS_MAX 0x08
#define ZCL_ATTRIB_FLAG_REPORTABLE 0x10
#define ZCL_ATTRIB_FLAG_UNUSED1 0x20
#define ZCL_ATTRIB_FLAG_RAW 0x40
Data is stored as sent/received in ZCL requests (little-endian, 24-bit types stored as 3 bytes instead of 4).
#define ZCL_ATTRIB_FLAG_FULL 0x80
If set, this is part of a zcl_attribute_full_t structure.
Detailed Description
Macro Definition Documentation
#define ZCL_ATTR_WRITE_FLAG_ASSIGN 0x01
Assign the new value to the attribute (if not set, just checks the validity of the data).
Referenced by _zcl_comm_startup_control_set(), _zcl_identify_time_set(), _zcl_time_time_set(), _zcl_time_timestatus_set(), _zcl_write_attributes(), zcl_decode_attribute(), zcl_parse_attribute_record(), and zcl_process_read_attr_response().
#define ZCL_ATTRIB_FLAG_RAW 0x40
Data is stored as sent/received in ZCL requests (little-endian, 24-bit types stored as 3 bytes instead of 4).
Not applicable to string types.
Referenced by zcl_decode_attribute(), and zcl_encode_attribute_value().
#define ZCL_CMD_DEFAULT_RESP 0x0b
Default Response Command, payload is 2 bytes; Command ID and Status Code (zcl_default_response_t).
Referenced by zcl_command_dump(), zcl_default_response(), and zcl_general_command().
#define ZCL_CMD_DISCOVER_ATTRIB 0x0c
Discover Attributes Command, payload is 3 bytes; start attribute ID and maximum number of attributes to return (zcl_discover_attrib_t).
Referenced by zcl_general_command().
#define ZCL_CMD_DISCOVER_ATTRIB_RESP 0x0d
Discover Attributes Response Command payload is a `discovery complete` byte (done = ZCL_BOOL_TRUE, more attributes = ZCL_BOOL_TRUE), followed by 1 to n 3-byte Attribute Report fields (zcl_rec_attrib_report_t).
Referenced by _zcl_discover_attributes(), and zcl_general_command().
#define ZCL_CMD_IS_CLUSTER(p)
Value:
(ZCL_FRAME_TYPE_CLUSTER == \
   ((const uint8_t FAR *)(p) & (ZCL_FRAME_TYPE_MASK
       | ZCL_FRAME_MFG_SPECIFIC)))
Identify cluster commands that are not manufacturer-specific, using the frame control field of a ZCL command.
Parameters
in p pointer to first byte of payload
Return values
TRUE ZCL command is manufacturer and cluster-specific
FALSE ZCL command doesn't have the manufacturer-specific bit set, or is a profile-wide command
#define ZCL_CMD_IS_MFG_CLUSTER(p)
Value:
((ZCL_FRAME_TYPE_CLUSTER | ZCL_FRAME_MFG_SPECIFIC
      ) == \
   ((const uint8_t FAR *)(p) & (ZCL_FRAME_TYPE_MASK
       | ZCL_FRAME_MFG_SPECIFIC)))
Identify manufacturer-specific cluster commands using the frame control field of a ZCL command.
Parameters
in p pointer to first byte of payload
Return values
TRUE ZCL command is manufacturer and cluster-specific
FALSE ZCL command doesn't have the manufacturer-specific bit set, or is a profile-wide command
#define ZCL_CMD_IS_PROFILE(p) (ZCL_FRAME_TYPE_PROFILE == ((const uint8_t FAR *)(p) & ZCL_FRAME_TYPE_MASK))
Identify profile commands (as opposed to cluster commands) using the frame control field of a ZCL command.
Ignores the manufacturer-specific bit (which specifies use of manufacturer-specific attributes).
Parameters
in p pointer to first byte of payload
Return values
TRUE ZCL command is not cluster-specific (profile command)
FALSE ZCL command is cluster-specific
#define ZCL_CMD_MATCH(p, mfg, dir, type)
Value:
((*(const uint8_t FAR *)(p) & \
   (ZCL_FRAME_MFG_SPECIFIC | ZCL_FRAME_DIRECTION
       | ZCL_FRAME_TYPE_MASK)) == \
   (ZCL_FRAME_ ## mfg | ZCL_FRAME_ ## dir | ZCL_FRAME_TYPE_ ## type))
Macro for checking the frame control field of a ZCL command.
Used to filter out commands that are (or are not) handled by the current function.
Parameters
in p pointer to first byte of payload (typically envelope->payload when called from a standard ZCL command handler, or the address of frame_control from a zcl_command_t built with zcl_command_build)
in mfg either MFG_SPECIFIC or GENERAL
in dir either CLIENT_TO_SERVER or SERVER_TO_CLIENT
in type either PROFILE (e.g., general commands) or CLUSTER (cluster-specific command)
Return values
TRUE ZCL command matches all three filters
FALSE ZCL command does not match
Referenced by _zcl_basic_server(), _zcl_onoff_handler(), zcl_identify_command(), and zcl_time_client().
#define ZCL_CMD_READ_ATTRIB_RESP 0x01
Read Attributes Response Command, payload is 1 to n variable-length Read Attribute Status records (zcl_rec_read_attrib_status_t).
Referenced by _zcl_read_attributes(), zcl_general_command(), and zcl_time_client().
#define ZCL_CMD_WRITE_ATTRIB 0x02
Write Attributes Command, payload is 1 to n variable-length Write Attribute Record fields (same as zcl_attrib_t).
Referenced by zcl_general_command(), and zcl_send_write_attributes().
#define ZCL_CMD_WRITE_ATTRIB_NORESP 0x05
Write Attributes No Response Command, same payload as Write Attributes Command (ZCL_CMD_WRITE_ATTRIB), handled as a Write Attributes Command except the response is not sent.
Referenced by _zcl_write_attributes(), and zcl_general_command().
#define ZCL_CMD_WRITE_ATTRIB_UNDIV 0x03
Write Attributes Undivided Command, same payload as Write Attributes Command (zcl_attrib_t), but attributes are only written if all attributes can be written successfully.
Referenced by _zcl_write_attributes(), and zcl_general_command().
Typedef Documentation
zcl_attrib_t
Initial value:
{
   uint16_t id_le
General format for an attribute, used for Write Attributes and Report Attributes commands.
typedef uint_fast8_t(* zcl_attribute_update_fn)(const struct zcl_attribute_full_t FAR *entry)
Function pointer assigned to a ZCL attribute record, called to update the value of the given attribute.
Necessary for attributes that are tied to physical hardware (only updated when requested) or attributes that change over time (as with the ZCL Identify cluster).
If the return value is not ZCL_STATUS_SUCCESS, the ZCL Read Attributes handler will return that as an error in the response frame.
Parameters
in,out entry attribute to update
Return values
ZCL_STATUS_SUCCESS successfully updated value
ZCL_STATUS_HARDWARE_FAILURE unable to update value due to hardware problem
ZCL_STATUS_SOFTWARE_FAILURE unable to update value due to software problem
See Also
zcl_attribute_write_fn(), zcl_attribute_full_t
typedef int(* zcl_attribute_write_fn)(const struct zcl_attribute_full_t FAR *entry, zcl_attribute_write_rec_t *rec)
Function pointer assigned to a ZCL attribute record, called instead of zcl_decode_attribute() to process a Write Request for the attribute.
This function typically calls zcl_decode_attribute() to convert the request to a temporary variable and then perform additional checks on it before assigning to the actual variable.
Parameters
in entry attribute to update
in,out rec record from Write Request with new value
Returns
number of bytes consumed from Write Request
See Also
zcl_attribute_update_fn(), zcl_attribute_full_t
zcl_default_response_t
Initial value:
{
   uint8_t command
Used for ZCL_CMD_DEFAULT_RESP.
zcl_discover_attrib_resp_t
Initial value:
{
   
   uint8_t discovery_complete
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
zcl_discover_attrib_t
Initial value:
{
   uint16_t start_attrib_id_le
Used for ZCL_CMD_DISCOVER_ATTRIB.
zcl_header_common_t
Initial value:
{
   uint8_t sequence
Common portion of ZCL header (appears after optional Manufacturer Code)
zcl_header_nomfg_t
Initial value:
{
   uint8_t frame_control
ZLC header structure used when building a normal (non-manufacturer-specific response frame.
zcl_header_response_t
Initial value:
{
   union {
      PACKED_STRUCT {
         uint8_t frame_control;
         uint16_t mfg_code_le;
      } mfg;
      PACKED_STRUCT {
         uint16_t dummy;
         uint8_t frame_control;
      } std;
   } u
ZCL header structure used for building response frames that may or may not be manufacturer-specific.
Frame is sent starting with element .u.mfg.frame_control or .u.std.frame_control.
zcl_header_t
Initial value:
{
   uint8_t frame_control
General header for casting onto an incoming frame.
Reference .type.mfg if (.frame_control & ZCL_FRAME_MFG_SPECIFIC != 0). Reference .type.std otherwise.
zcl_header_withmfg_t
Initial value:
{
   uint8_t frame_control
ZLC header structure used when building a manufacturer-specific response frame.
zcl_read_struct_attrib_t
Initial value:
{
   uint16_t attrib_id_le
zcl_rec_attrib_report_t
Initial value:
{
   uint16_t id_le
Used for ZCL_CMD_DISCOVER_ATTRIB_RESP.
zcl_rec_read_attrib_array_resp_t
Initial value:
{
   uint16_t id_le
zcl_rec_read_attrib_error_resp_t
Initial value:
{
   uint16_t id_le
zcl_rec_read_attrib_resp_t
Initial value:
{
   uint16_t id_le
Used for ZCL_CMD_READ_ATTRIB_RESP.
zcl_rec_read_attrib_struct_resp_t
Initial value:
{
   uint16_t id_le
zcl_rec_read_report_cfg_t
Initial value:
{
   uint8_t direction
zcl_rec_report_error_resp_t
Initial value:
{
   uint8_t status
zcl_rec_report_receive_resp_t
Initial value:
{
   uint8_t status
zcl_rec_report_receive_t
Initial value:
{
   uint8_t direction
zcl_rec_report_send_resp_t
Initial value:
{
   uint8_t status
zcl_rec_report_send_t
Initial value:
{
   uint8_t direction
zcl_rec_reporting_status_t
Initial value:
{
   uint8_t status
zcl_rec_write_attrib_status_t
Initial value:
{
   uint8_t status
Used for ZCL_CMD_WRITE_ATTRIB_RESP.
zcl_rec_write_struct_attrib_resp_t
Initial value:
{
   uint8_t status
zcl_rec_write_struct_attrib_t
Initial value:
{
   uint16_t id_le
zcl_selector_t
Initial value:
{
   uint8_t indicator
Function Documentation
zigbee_zcl_debug int _zcl_discover_attributes (zcl_command_t * cmd)
Process the Discover Attributes Command (ZCL_CMD_DISCOVER_ATTRIB).
Parameters
in cmd command to respond to
Return values
0 successfully sent response
!0 error on send
References zcl_command_t::attributes, EINVAL, FAR, htole16, le16toh, PACKED_STRUCT, ZCL_ATTRIBUTE_END_OF_LIST, zcl_attribute_get_next(), zcl_build_header(), ZCL_CMD_DISCOVER_ATTRIB_RESP, zcl_command_t::zcl_payload, and zcl_send_response().
Referenced by zcl_general_command().
zigbee_zcl_debug int _zcl_encode_array_value (uint8_t FAR * buffer, int16_t bufsize, const zcl_array_t FAR * array)
Format a ZCL array for a Read Attributes Response or a Write Attributes Request.
Parameters
out buffer buffer to store encoded attribute
in bufsize number of bytes available in buffer
in array array to encode into buffer
Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames.
Return values
-ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value
-ZCL_STATUS_FAILURE unknown/unsupported attribute type
-ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value
-ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value
>=0 number of bytes written
See Also
zcl_encode_attribute_value
References FAR, and zcl_encode_attribute_value().
Referenced by zcl_encode_attribute_value().
zigbee_zcl_debug int _zcl_encode_struct_value (uint8_t FAR * buffer, int16_t bufsize, const zcl_struct_t FAR * zcl_struct)
Format a ZCL struct for a Read Attributes Response or a Write Attributes Request.
Parameters
out buffer buffer to store encoded attribute
in bufsize number of bytes available in buffer
in zcl_struct struct to encode into buffer
Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames.
Return values
-ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value
-ZCL_STATUS_FAILURE unknown/unsupported attribute type
-ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value
-ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value
>=0 number of bytes written
See Also
zcl_encode_attribute_value
References FAR, and zcl_encode_attribute_value().
Referenced by zcl_encode_attribute_value().
zigbee_zcl_debug int _zcl_read_attributes (zcl_command_t * cmd)
Process the Read Attributes Command (ZCL_CMD_READ_ATTRIB).
Parameters
in cmd command to respond to
Return values
0 successfully sent response
!0 error on send
-EINVAL NULL cmd parameter
References zcl_command_t::attributes, EINVAL, FAR, le16toh, zcl_command_t::length, PACKED_STRUCT, zcl_build_header(), ZCL_CMD_READ_ATTRIB_RESP, zcl_default_response(), zcl_encode_attribute_value(), zcl_find_attribute(), zcl_command_t::zcl_payload, and zcl_send_response().
Referenced by zcl_general_command().
zigbee_zcl_debug int _zcl_write_attributes (zcl_command_t * cmd)
Process the three types of Write Attributes requests.
Handles Write Attributes (ZCL_CMD_WRITE_ATTRIB), Write Attributes Undivided (ZCL_CMD_WRITE_ATTRIB_UNDIV) and Write Attributes No Response (ZCL_CMD_WRITE_ATTRIB_NORESP).
Parameters
in cmd command to respond to
Return values
0 successfully sent response or `No Response` requested
!0 error on send
Todo
Todo Generate error if command is not one of the three expected commands.
Todo
Todo Update to limit number of status records in response.
References zcl_command_t::attributes, zcl_attribute_write_rec_t::buffer, zcl_attribute_write_rec_t::buflen, zcl_command_t::command, FAR, zcl_attribute_write_rec_t::flags, hex_dump(), HEX_DUMP_FLAG_TAB, length, zcl_command_t::length, PACKED_STRUCT, status, zcl_attribute_write_rec_t::status, ZCL_ATTR_WRITE_FLAG_ASSIGN, zcl_build_header(), ZCL_CMD_WRITE_ATTRIB_NORESP, ZCL_CMD_WRITE_ATTRIB_RESP, ZCL_CMD_WRITE_ATTRIB_UNDIV, zcl_parse_attribute_record(), zcl_command_t::zcl_payload, and zcl_send_response().
Referenced by zcl_general_command().
const zcl_attribute_base_t FAR * zcl_attribute_get_next (const zcl_attribute_base_t FAR * entry)
Return a pointer to the next attribute entry from an attribute table.
Parameters
in entry current entry from the table
Return values
NULL entry was NULL
!NULL pointer to next attribute record
Note
If entry points to the last entry in the table, this function will return the same address instead of advancing off the end of the table.
See Also
zcl_find_attribute
References FAR, ZCL_ATTRIB_FLAG_FULL, and ZCL_ATTRIBUTE_END_OF_LIST.
Referenced by _zcl_discover_attributes(), zcl_create_attribute_records(), and zcl_find_attribute().
int zcl_build_header (zcl_header_response_t * rsp, zcl_command_t * cmd)
Support function to fill in a ZCL response header.
Set the frame_control, sequence and optional mfg_code fields of the ZCL response header, and return the offset to the actual start of the header (non-mfg specific skips the first two bytes).
Parameters
out rsp buffer to store header of response
in cmd command we're responding to
Return values
0 responding to manufacturer-specific command
2 responding to non-manufacturer-specific command
-EINVAL invalid parameter passed to function
References EINVAL, zcl_command_t::frame_control, htole16, zcl_command_t::mfg_code, zcl_command_t::sequence, ZCL_FRAME_DIRECTION, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_MFG_SPECIFIC, and ZCL_FRAME_TYPE_MASK.
Referenced by _zcl_discover_attributes(), _zcl_read_attributes(), _zcl_write_attributes(), zcl_default_response(), and zcl_identify_command().
int zcl_check_minmax (const zcl_attribute_base_t FAR * entry, const uint8_t FAR * buffer_le)
Checks whether a new value from a Write Attributes command is within the limits specified for a given attribute.
Parameters
in entry entry to use for min/max check
in buffer_le buffer with new value (in little-endian byte order), from write attributes command
Return values
0 new value is within range (or attribute doesn't have a min/max)
-EINVAL invalid parameter passed to function
!0 value is out of range
References EINVAL, FAR, memcpy_letoh, value, zcl_sizeof_type(), ZCL_T_FLOAT, ZCL_T_SIGNED, and zcl_type_info.
Referenced by zcl_parse_attribute_record().
int zcl_command_build (zcl_command_t * cmd, const wpan_envelope_t FAR * envelope, zcl_attribute_tree_t FAR * tree)
Parse a ZCL request and store in a zcl_command_t structure with fields in fixed locations (therefore easier to use than the variable-length frame header).
Also uses the direction bit and manufacturer ID to search the attribute tree for the correct list of attributes.
Parameters
out cmd buffer to store parsed ZCL command
in envelope envelope from received message
in tree pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher)
Return values
0 parsed payload from envelope into cmd
-EINVAL invalid parameter passed to function
-EBADMSG frame is too small for ZCL header's frame_control value
References zcl_command_t::attributes, command, zcl_command_t::command, EBADMSG, EINVAL, zcl_command_t::envelope, FAR, zcl_command_t::frame_control, le16toh, zcl_command_t::length, zcl_command_t::mfg_code, zcl_command_t::sequence, ZCL_FRAME_CLIENT_TO_SERVER, ZCL_FRAME_DIRECTION, ZCL_FRAME_MFG_SPECIFIC, and zcl_command_t::zcl_payload.
Referenced by _zcl_basic_server(), _zcl_onoff_handler(), zcl_envelope_payload_dump(), zcl_general_command(), zcl_identify_command(), zcl_invalid_cluster(), zcl_invalid_command(), and zcl_time_client().
void zcl_command_dump (const zcl_command_t * cmd)
Debugging routine that dumps contents of a parsed ZCL command structure to STDOUT.
Parameters
in cmd zcl_command_t structure populated by zcl_command_build()
References _TABLE_ENTRIES, zcl_command_t::command, FAR, zcl_command_t::frame_control, hex_dump(), HEX_DUMP_FLAG_TAB, length, zcl_command_t::length, zcl_command_t::mfg_code, zcl_command_t::sequence, ZCL_CMD_DEFAULT_RESP, ZCL_CMD_WRITE_ATTRIB_RESP, ZCL_FRAME_CLIENT_TO_SERVER, ZCL_FRAME_DIRECTION, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_TYPE_MASK, ZCL_FRAME_TYPE_PROFILE, zcl_command_t::zcl_payload, and zcl_status_text().
Referenced by zcl_envelope_payload_dump().
uint32_t zcl_convert_24bit (const void FAR * value_le, bool_t extend_sign)
Convert a 24-bit (3-byte) little-endian value to a 32-bit value in host byte order.
Parameters
in value_le pointer to 3 bytes to convert
in extend_sign if TRUE, set high byte of result to 0xFF if top bit of 24-bit value is set
Returns
A 32-bit, host-byte-order version of the 24-bit, little-endian value passed in.
References FAR.
Referenced by zcl_decode_attribute().
int zcl_decode_attribute (const zcl_attribute_base_t FAR * entry, zcl_attribute_write_rec_t * rec)
Decode attribute value from a Write Attribute Request or Read Attribute Response record and optionally write to entry.
Parameters
in entry entry from attribute table
in,out rec state information for parsing write request
Return values
>=0 number of bytes consumed from rec->buffer
-EINVAL invalid parameter passed to function
References zcl_attribute_write_rec_t::buffer, zcl_attribute_write_rec_t::buflen, EINVAL, FAR, zcl_attribute_write_rec_t::flags, length, memcpy_letoh, PRIsFAR, PRIx32, zcl_attribute_write_rec_t::status, ZCL_ATTR_WRITE_FLAG_ASSIGN, ZCL_ATTRIB_FLAG_FULL, ZCL_ATTRIB_FLAG_RAW, zcl_convert_24bit(), zcl_sizeof_type(), ZCL_TYPE_IS_INVALID, ZCL_TYPE_STRING_CHAR, and ZCL_TYPE_UNKNOWN.
Referenced by _zcl_identify_time_set(), _zcl_time_time_set(), and zcl_parse_attribute_record().
int zcl_default_response (zcl_command_t * request, uint8_t status)
Send a Default Response (ZCL_CMD_DEFAULT_RESP) to a given command.
Parameters
in request command we're responding to
in status status to use in the response (see ZCL_STATUS_* macros under `ZCL Status Enumerations` in zigbee/zcl.h)
Return values
0 successfully sent response, or response not required (message was broadcast, sent to the broadcast endpoint, or sender set the disable default response bit)
!0 error on send
-EINVAL invalid parameter passed to function
References command, zcl_command_t::command, EINVAL, zcl_command_t::envelope, zcl_command_t::frame_control, PACKED_STRUCT, status, WPAN_ENVELOPE_BROADCAST_ADDR, WPAN_ENVELOPE_BROADCAST_EP, zcl_build_header(), ZCL_CMD_DEFAULT_RESP, ZCL_FRAME_DISABLE_DEF_RESP, ZCL_FRAME_TYPE_MASK, ZCL_FRAME_TYPE_PROFILE, and zcl_send_response().
Referenced by _zcl_basic_server(), _zcl_onoff_handler(), _zcl_read_attributes(), zcl_identify_command(), zcl_invalid_cluster(), zcl_invalid_command(), and zcl_time_client().
int zcl_encode_attribute_value (uint8_t FAR * buffer, int16_t bufsize, const zcl_attribute_base_t FAR * entry)
Format a ZCL attribute's value for a Read Attributes Response or a Write Attributes Request.
Copies the value of attribute entry to buffer in little-endian byte order. Will not write more than bufsize bytes. Used to build ZCL frames.
Parameters
out buffer buffer to store encoded attribute
in bufsize number of bytes available in buffer
in entry attribute to encode into buffer
Return values
-ZCL_STATUS_SOFTWARE_FAILURE invalid parameter passed in
-ZCL_STATUS_DEFINED_OUT_OF_BAND ghost attribute with NULL value
-ZCL_STATUS_INSUFFICIENT_SPACE buffer too small to encode value
-ZCL_STATUS_FAILURE unknown/unsupported attribute type
-ZCL_STATUS_HARDWARE_FAILURE failure updating attribute value
-ZCL_STATUS_SOFTWARE_FAILURE failure updating attribute value
>=0 number of bytes written
References _zcl_encode_array_value(), _zcl_encode_struct_value(), FAR, memcpy_htole, status, type, ZCL_ATTRIB_FLAG_FULL, ZCL_ATTRIB_FLAG_RAW, zcl_sizeof_type(), ZCL_TYPE_ARRAY, ZCL_TYPE_BAG, ZCL_TYPE_IS_INVALID, ZCL_TYPE_SET, ZCL_TYPE_STRING_CHAR, and ZCL_TYPE_STRUCT.
Referenced by _zcl_encode_array_value(), _zcl_encode_struct_value(), _zcl_read_attributes(), and zcl_create_attribute_records().
void zcl_envelope_payload_dump (const wpan_envelope_t * envelope)
Debugging routine that parses an envelope payload as a ZCL command and dumps a parsed copy to STDOUT.
Parameters
in envelope wpan_envelope_t structure with a ZCL command payload
References hex_dump(), HEX_DUMP_FLAG_OFFSET, wpan_envelope_t::length, wpan_envelope_t::payload, zcl_command_build(), and zcl_command_dump().
const zcl_attribute_base_t FAR * zcl_find_attribute (const zcl_attribute_base_t FAR * entry, uint16_t search_id)
Search the attribute table starting at entry, for attribute ID search_id.
Parameters
in entry starting entry for search
in search_id attribute ID to look for
Return values
NULL attribute id search_id not in list
!NULL pointer to attribute record
References zcl_attribute_get_next().
Referenced by _zcl_read_attributes(), and zcl_parse_attribute_record().
int zcl_general_command (const wpan_envelope_t FAR * envelope, void FAR * context)
Handler for ZCL General Commands.
Used as the handler for attribute-only clusters (e.g., Basic Cluster), or called from a cluster's handler for commands it doesn't handle.
Will send a Default Response for commands it can't handle.
Currently does not support attribute reporting.
Parameters
in envelope envelope from received message
in context pointer to attribute tree for cluster or NULL if the cluster doesn't have any attributes (typically passed in via endpoint dispatcher)
Return values
0 command was processed, including sending a possible response
!0 error sending response or processing command
References _zcl_discover_attributes(), _zcl_read_attributes(), _zcl_write_attributes(), zcl_command_t::command, FAR, zcl_command_t::frame_control, hex_dump(), HEX_DUMP_FLAG_TAB, zcl_command_t::sequence, wpan_conversation_response(), ZCL_CMD_DEFAULT_RESP, ZCL_CMD_DISCOVER_ATTRIB, ZCL_CMD_DISCOVER_ATTRIB_RESP, ZCL_CMD_READ_ATTRIB, ZCL_CMD_READ_ATTRIB_RESP, ZCL_CMD_WRITE_ATTRIB, ZCL_CMD_WRITE_ATTRIB_NORESP, ZCL_CMD_WRITE_ATTRIB_RESP, ZCL_CMD_WRITE_ATTRIB_UNDIV, zcl_command_build(), ZCL_FRAME_TYPE_MASK, ZCL_FRAME_TYPE_PROFILE, zcl_invalid_command(), zcl_command_t::zcl_payload, and zcl_status_text().
Referenced by _zcl_basic_server(), _zcl_onoff_handler(), zcl_identify_command(), and zcl_time_client().
int zcl_invalid_cluster (const wpan_envelope_t FAR * envelope, wpan_ep_state_t FAR * ep_state)
Called if a request comes in for an invalid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) of #ZCL_STATUS_FAILURE unless the received command was a Default Response or was broadcast.
Parameters
in envelope envelope from received message
in ep_state pointer to endpoint's wpan_ep_state_t
Return values
0 command was a default response (and therefore ignored), or a default response was successfully sent
!0 error sending response
References XBEE_UNUSED_PARAMETER, zcl_command_build(), and zcl_default_response().
Referenced by _wpan_endpoint_dispatch().
int zcl_invalid_command (const wpan_envelope_t FAR * envelope)
Called if a request comes in for an invalid command on a valid endpoint/cluster combination.
Sends a Default Response (ZCL_CMD_DEFAULT_RESP) unless the received command was a Default Response or was broadcast. Depending on the command received, the response will be one of:
ZCL_STATUS_UNSUP_CLUSTER_COMMAND
ZCL_STATUS_UNSUP_GENERAL_COMMAND
ZCL_STATUS_UNSUP_MANUF_CLUSTER_COMMAND
ZCL_STATUS_UNSUP_MANUF_GENERAL_COMMAND
Parameters
in envelope envelope from received message
Return values
0 default response was successfully sent, or command did not require a default response
!0 error building or sending response
References zcl_command_t::command, zcl_command_t::frame_control, status, zcl_command_build(), zcl_default_response(), ZCL_FRAME_MFG_SPECIFIC, ZCL_FRAME_TYPE_CLUSTER, and ZCL_FRAME_TYPE_MASK.
Referenced by zcl_general_command().
int zcl_parse_attribute_record (const zcl_attribute_base_t FAR * entry, zcl_attribute_write_rec_t * write_rec)
Parse an attribute record from a Write Attributes Request or a Read Attributes Response and possibly store the new attribute value.
If ZCL_ATTR_WRITE_FLAG_READ_RESP is set in write_rec->flags, write_rec->buffer will be parsed as a Read Attributes Response record. Otherwise, it's parsed as a Write Attributes Request record.
Parameters
in entry attribute table to search or NULL if there aren't any attributes on this cluster
in,out write_rec state information for parsing write request
Return values
>=0 number of bytes consumed from buffer
-EINVAL invalid parameter passed to function
Todo
Todo should we set a flag in write_rec to indicate that the status was not success?
References zcl_attribute_write_rec_t::buffer, zcl_attribute_write_rec_t::buflen, EINVAL, FAR, zcl_attribute_write_rec_t::flags, le16toh, zcl_attribute_write_rec_t::status, type, zcl_attribute_base_t::type, ZCL_ATTR_WRITE_FLAG_ASSIGN, ZCL_ATTR_WRITE_FLAG_READ_RESP, ZCL_ATTRIB_FLAG_FULL, zcl_check_minmax(), zcl_decode_attribute(), zcl_find_attribute(), zcl_sizeof_type(), and ZCL_TYPE_IS_INVALID.
Referenced by _zcl_write_attributes(), and zcl_process_read_attr_response().
int zcl_send_response (zcl_command_t * request, const void FAR * response, uint16_t length)
Send a response to a ZCL command.
Uses information from the command received to populate fields in the response.
Parameters
in request command to respond to
in response payload to send as response
in length number of bytes in response
Return values
0 successfully sent response
!0 error on send
References EINVAL, zcl_command_t::envelope, wpan_envelope_t::length, length, wpan_envelope_t::payload, wpan_envelope_dump(), wpan_envelope_reply(), and wpan_envelope_send().
Referenced by _zcl_discover_attributes(), _zcl_read_attributes(), _zcl_write_attributes(), zcl_default_response(), and zcl_identify_command().
const char * zcl_status_text (uint_fast8_t status)
Converts a ZCL status byte (one of the ZCL_STATUS_* macros) into a string.
Parameters
in status status byte to convert
Returns
pointer to an unmodifiable string with a description of the status
Referenced by zcl_command_dump(), and zcl_general_command().
Variable Documentation
const zcl_attribute_base_t FAR* attributes
Appropriate list of attributes on this device, related to the command.
Based on the direction bit from frame_control and the mfg_code field.
Referenced by _zcl_discover_attributes(), _zcl_read_attributes(), _zcl_write_attributes(), and zcl_command_build().
zcl_attribute_minmax_t max
Maximum value for attribute, assumes 32-bit limit.
For string attributes, the maximum length that can be stored at value.
zcl_attribute_minmax_t min
Minimum value for attribute (currently unused until I pick a value to represent `none`).
PACKED_STRUCT
Initial value:
{
         uint16_t mfg_code_le
PACKED_STRUCT
Initial value:
{
         uint16_t mfg_code_le
PACKED_STRUCT
Initial value:
{
      uint8_t direction
zcl_attribute_update_fn read
On an attribute read, the ZCL dispatcher will call the .read function to refresh the attribute's value before responding to the request.
Do I need a return value in the function to pass an error up?
uint8_t status
Set to #ZCL_STATUS_SUCCESS if data is valid, or some other ZCL_STATUS_* macro if there's an error.
Referenced by _zcl_comm_startup_control_set(), _zcl_time_time_set(), _zcl_write_attributes(), zcl_decode_attribute(), zcl_parse_attribute_record(), and zcl_process_read_attr_response().
uint8_t type
see zigbee/zcl_types.h
always ZCL_TYPE_STRUCT
one of ZCL_TYPE_ARRAY, ZCL_TYPE_SET, ZCL_TYPE_BAG
only included if status == ZCL_STATUS_SUCCESS
Referenced by _zdo_match_desc_respond(), xbee_frame_write(), zcl_encode_attribute_value(), zcl_parse_attribute_record(), zcl_print_array_value(), zcl_print_struct_value(), zcl_sizeof_type(), and zdo_send_bind_req().
uint8_t value[1]
variable length, depending on type
variable length, only if ZCL_STATUS_SUCCESS
const void FAR* value
Pointer to global variable of correct type, set as const to allow for both const and non-const values.
(If const, flags should be include #ZCL_ATTRIB_FLAG_READONLY.) If NULL, the ZCL stack will respond to attempts to read/write with ZCL_STATUS_DEFINED_OUT_OF_BAND.
zcl_attribute_write_fn write
On an attribute write, the ZCL dispatcher will call the .write function with a structure containing information about the write request.
See the documentation for zcl_attribute_write_fn() for the API, and the Time and Identify clusters for examples of its use.
const zcl_attribute_tree_t FAR zcl_attributes_none[1]
Initial value:
=
   { { ZCL_MFG_NONE, NULL, NULL } }
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
Don't use NULL, since the APS dispatcher will use endpoint's context if the cluster's context is NULL.
const zcl_attribute_tree_t FAR zcl_attributes_none[1]
If a cluster doesn't have attributes, use zcl_attributes_none (a single, empty attribute list) in the cluster definition.
Don't use NULL, since the APS dispatcher will use endpoint's context if the cluster's context is NULL.