Client
Code for a device to send over-the-air firmware updates to a Programmable XBee.
Files
file xbee_ota_client.c
Support code for over-the-air (OTA) firmware updates of application code on Programmable XBee target.
file ota_client.h
Support code for over-the-air (OTA) firmware updates of application code on Programmable XBee target.
Data Structures
struct xbee_ota_t
Structure for tracking state of over-the-air update.
Macros
#define XBEE_OTA_MAX_AUTH_LENGTH 64
#define XBEE_OTA_FLAG_APS_ENCRYPT 0x0001
Send data with APS encryption.
#define XBEE_OTA_DATA_CLIENT_CLUST_ENTRY(ota, flags)
Macro for adding the OTA receive cluster (Digi Transparent Serial) to the cluster list for WPAN_ENDPOINT_DIGI_DATA.
#define XBEE_OTA_CMD_CLIENT_CLUST_ENTRY(handler, context, flag)
Functions
int _xbee_ota_transparent_rx (const wpan_envelope_t FAR *envelope, void FAR *context)
Cluster handler for `Digi Transparent Serial` cluster.
int _xbee_ota_xmodem_read (void FAR *context, void FAR *buffer, int16_t bytes)
int _xbee_ota_xmodem_write (void FAR *context, const void FAR *buffer, int16_t bytes)
int xbee_ota_init (xbee_ota_t *ota, wpan_dev_t *dev, const addr64 *target)
Initialize an xbee_ota_t structure to send firmware updates to target using dev.
Variables
wpan_dev_t * dev
local device to send updates through
addr64 target
network device to update
uint16_t flags
combination of XBEE_OTA_FLAG_* values
xbee_cbuf_t cbuf
track state of circular buffer
uint8_t raw [255+XBEE_CBUF_OVERHEAD]
buffer for xbee_cbuf_t structure and bytes received from target
xx xx xx xx xx xx xx xx xx
union {
 xbee_cbuf_t cbuf
  track state of circular buffer
 uint8_t raw [255+XBEE_CBUF_OVERHEAD]
  buffer for xbee_cbuf_t structure and bytes received from target
} rxbuf
xbee_xmodem_state_t xbxm
track state of Xmodem transfer
uint8_t auth_data [XBEE_OTA_MAX_AUTH_LENGTH]
Payload used to initiate update.
uint8_t auth_length
Number of bytes in auth_data.
Detailed Description
Code for a device to send over-the-air firmware updates to a Programmable XBee.
Macro Definition Documentation
#define XBEE_OTA_CMD_CLIENT_CLUST_ENTRY(handler, context, flag)
Value:
{ DIGI_CLUST_PROG_XBEE_OTA_UPD, handler,
      \
      context, (flag) | WPAN_CLUST_FLAG_CLIENT |
      WPAN_CLUST_FLAG_NOT_ZCL }
#define XBEE_OTA_DATA_CLIENT_CLUST_ENTRY(ota, flags)
Value:
{ DIGI_CLUST_SERIAL, _xbee_ota_transparent_rx
      , ota, \
      WPAN_CLUST_FLAG_INOUT | WPAN_CLUST_FLAG_NOT_ZCL |
      flags }
Macro for adding the OTA receive cluster (Digi Transparent Serial) to the cluster list for WPAN_ENDPOINT_DIGI_DATA.
Parameters
in ota pointer to an xbee_ota_t structure for tracking update state
in flags additional flags for the cluster; typically 0 or WPAN_CLUST_FLAG_ENCRYPT
Function Documentation
int _xbee_ota_transparent_rx (const wpan_envelope_t FAR * envelope, void FAR * context)
Cluster handler for `Digi Transparent Serial` cluster.
Used in the cluster table of WPAN_ENDPOINT_DIGI_DATA (0xE8) for cluster DIGI_CLUST_SERIAL (0x0011).
This is a preliminary API and WILL change in a future release. This version is dedicated to processing responses in OTA (over-the-air) firmware updates and has not been generalized for other uses.
Parameters
in envelope information about the frame (addresses, endpoint, profile, cluster, etc.)
in,out context pointer to xbee_ota_t structure
Return values
0 handled data
!0 some sort of error processing data
See Also
wpan_aps_handler_fn()
References FAR, hex_dump(), HEX_DUMP_FLAG_TAB, and xbee_cbuf_put().
int _xbee_ota_xmodem_read (void FAR * context, void FAR * buffer, int16_t bytes)
Function assigned to the stream.read function pointer of an xbee_xmodem_state_t object. Reads data from the target specified in the xbee_ota_t structure.
Parameters
in context xbee_ota_t structure
in,out buffer buffer to store read data
in bytes maximum number of bytes to write to buffer
See Also
xbee_xmodem_read_fn()
References EINVAL, FAR, and xbee_cbuf_get().
Referenced by xbee_ota_init().
int _xbee_ota_xmodem_write (void FAR * context, const void FAR * buffer, int16_t bytes)
Function assigned to the stream.write function pointer of an xbee_xmodem_state_t object. Sends data to the target specified in the xbee_ota_t structure.
Parameters
in context xbee_ota_t structure
in,out buffer source of data to send
in bytes number of bytes to send
Returns
Number of bytes sent to target.
See Also
xbee_xmodem_write_fn()
References wpan_envelope_t::dev, EINVAL, FAR, wpan_envelope_t::length, wpan_envelope_t::payload, WPAN_CLUST_FLAG_ENCRYPT, wpan_envelope_create(), WPAN_NET_ADDR_UNDEFINED, XBEE_OTA_FLAG_APS_ENCRYPT, and xbee_transparent_serial().
Referenced by xbee_ota_init().
int xbee_ota_init (xbee_ota_t * ota, wpan_dev_t * dev, const addr64 * target)
Initialize an xbee_ota_t structure to send firmware updates to target using dev.
Calls xbee_xmodem_tx_init and xbee_xmodem_set_stream (therefore unnecessary to do so in main program).
Note that when performing OTA updates, you MUST use XBEE_XMODEM_FLAG_64 (64-byte xmodem blocks) if calling xbee_xmodem_tx_init directly.
Sends frames to the target to have it start the update cycle.
Parameters
in,out ota state-tracking structure for sending update
in dev device to use for sending update
in target 64-bit address of target device
Return values
0 successfully initialized
-EINVAL invalid parameter passed in
References _xbee_ota_xmodem_read(), _xbee_ota_xmodem_write(), xbee_ota_t::auth_data, xbee_ota_t::auth_length, xbee_ota_t::cbuf, wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, xbee_ota_t::dev, DIGI_CLUST_PROG_XBEE_OTA_UPD, DIGI_CLUST_SERIAL, EINVAL, xbee_ota_t::flags, wpan_envelope_t::length, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, xbee_ota_t::target, WPAN_CLUST_FLAG_ENCRYPT, WPAN_ENDPOINT_DIGI_DATA, wpan_envelope_create(), wpan_envelope_send(), WPAN_NET_ADDR_UNDEFINED, WPAN_PROFILE_DIGI, xbee_cbuf_init(), XBEE_OTA_FLAG_APS_ENCRYPT, XBEE_XMODEM_FLAG_64, xbee_xmodem_set_stream(), xbee_xmodem_tx_init(), and xbee_ota_t::xbxm.