Glue layer between XBee Device driver and WPAN
network stack.
Files
file xbee_wpan.c
Glue layer between XBee-specific code and general WPAN layer.
file wpan.h
Macros
#define xbee_wpan_debug
#define XBEE_FRAME_HANDLE_RX_EXPLICIT { XBEE_FRAME_RECEIVE_EXPLICIT, 0, _xbee_handle_receive_explicit, NULL }
#define XBEE_TX_OPT_DISABLE_ACK 0x01
XBee Transmit Option: Disable ACK [ZigBee and DigiMesh].
#define XBEE_TX_OPT_DISABLE_ROUTE_DISC 0x02
XBee Transmit Option: Disable Route Discovery [DigiMesh].
#define XBEE_TX_OPT_ENABLE_UNICAST_NACK 0x04
XBee Transmit Option: Enable Unicast NACK messages [DigiMesh].
#define XBEE_TX_OPT_ENABLE_UNICAST_TRACE 0x08
XBee Transmit Option: Enable Unicast Trace Route messages [DigiMesh].
#define XBEE_TX_OPT_APS_ENCRYPT 0x20
XBee Transmit Option: Enable APS encryption (if EE=1) [ZigBee].
#define XBEE_TX_OPT_EXTENDED_TIMEOUT 0x40
XBee Transmit Option: Use extended timeout for this destination. [ZigBee].
#define XBEE_TX_OPT_MODE_POINT_MULTIPOINT (1<<6)
XBee Transmit Option: Point-Multipoint [DigiMesh].
#define XBEE_TX_OPT_MODE_REPEATER (2<<6)
XBee Transmit Option: Repeater mode (directed broadcast) [DigiMesh].
#define XBEE_TX_OPT_MODE_DIGIMESH (3<<6)
XBee Transmit Option: DigiMesh (not available on 10k product) [DigiMesh].
Typedefs
typedef PACKED_STRUCT xbee_frame_receive_explicit_t
Format of XBee API frame type 0x91 (XBEE_FRAME_RECEIVE_EXPLICIT); received from XBee by host.
typedef PACKED_STRUCT xbee_header_transmit_t
Format of XBee API frame type 0x10 (XBEE_FRAME_TRANSMIT); sent from host to XBee.
typedef PACKED_STRUCT xbee_header_transmit_explicit_t
Format of XBee API frame type 0x11 (XBEE_FRAME_TRANSMIT_EXPLICIT); sent from host to XBee.
Functions
xbee_wpan_debug int _xbee_handle_receive_explicit (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Process XBee `Receive Explicit` frames (type 0x91) and hand off to wpan_envelope_dispatch() for further processing.
int _xbee_endpoint_send (const wpan_envelope_t FAR *envelope, uint16_t flags)
xbee_wpan_debug int _xbee_wpan_tick (wpan_dev_t *dev)
xbee_wpan_debug int xbee_wpan_init (xbee_dev_t *xbee, const wpan_endpoint_table_entry_t *ep_table)
Configure xbee_dev_t for APS-layer (endpoint/cluster) networking.
xbee_wpan_debug int _xbee_handle_transmit_status (xbee_dev_t *xbee, const void FAR *payload, uint16_t length, void FAR *context)
Variables
XBEE_BEGIN_DECLS typedef
*
PACKED_STRUCT xbee_frame_receive_t
Format of XBee API frame type 0x90 (XBEE_FRAME_RECEIVE); received from XBee by host.
addr64 ieee_address
uint16_t network_address_be
uint8_t options
bitfield, see XBEE_RX_OPT_xxx macros
uint8_t payload [1]
multi-byte payload
uint8_t source_endpoint
uint8_t dest_endpoint
uint16_t cluster_id_be
uint16_t profile_id_be
uint8_t frame_id
uint8_t broadcast_radius
set to 0 for maximum hop value
Detailed Description
network stack.
Typedef Documentation
xbee_frame_receive_explicit_t
Initial value:
{
   uint8_t frame_type
Format of XBee API frame type 0x91 (XBEE_FRAME_RECEIVE_EXPLICIT); received from XBee by host.
XBEE_FRAME_RECEIVE_EXPLICIT (0x91)
xbee_header_transmit_explicit_t
Initial value:
{
   uint8_t frame_type
Format of XBee API frame type 0x11 (XBEE_FRAME_TRANSMIT_EXPLICIT); sent from host to XBee.
XBEE_FRAME_TRANSMIT_EXPLICIT (0x11)
xbee_header_transmit_t
Initial value:
{
   uint8_t frame_type
Format of XBee API frame type 0x10 (XBEE_FRAME_TRANSMIT); sent from host to XBee.
Note that the network stack does not include a function for sending this frame type -- use an explicit transmit frame instead (type 0x11) with WPAN_ENDPOINT_DIGI_DATA as the source and destination endpoint, DIGI_CLUST_SERIAL as the cluster ID and WPAN_PROFILE_DIGI as the profile ID. Or, use the xbee_transparent_serial() function from xbee_transparent_serial.c to fill in those fields and send the data. XBEE_FRAME_TRANSMIT (0x10)
Function Documentation
xbee_wpan_debug int _xbee_endpoint_send (const wpan_envelope_t FAR * envelope, uint16_t flags)
Sends data to an endpoint/profile/cluster on a remote WPAN node. See wpan_endpoint_send_fn() for parameters and return values.
User code should use wpan_envelope_send() instead of calling this function directly.
References htobe16, XBEE_FRAME_TRANSMIT_EXPLICIT, xbee_frame_write(), xbee_next_frame_id(), and XBEE_TX_OPT_APS_ENCRYPT.
Referenced by xbee_wpan_init().
int _xbee_handle_receive_explicit (xbee_dev_t * xbee, const void FAR * raw, uint16_t length, void FAR * context)
Process XBee `Receive Explicit` frames (type 0x91) and hand off to wpan_envelope_dispatch() for further processing.
Please view the function help for xbee_frame_handler_fn() for details on this function's parameters and possible return values.
References be16toh, wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, EBADMSG, EINVAL, FAR, wpan_envelope_t::ieee_address, wpan_envelope_t::length, wpan_envelope_t::network_address, payload, wpan_envelope_t::payload, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, xbee_dev_t::wpan_dev, WPAN_ENVELOPE_BROADCAST_ADDR, wpan_envelope_dispatch(), WPAN_ENVELOPE_RX_APS_ENCRYPT, XBEE_RX_OPT_APS_ENCRYPT, XBEE_RX_OPT_BROADCAST, and XBEE_UNUSED_PARAMETER.
xbee_wpan_debug int _xbee_handle_transmit_status (xbee_dev_t * xbee, const void FAR * frame, uint16_t length, void FAR * context)
Dummy frame handler for 0x8B (XBEE_FRAME_TRANSMIT_STATUS) frames. Placeholder until we integrate processing of those frames into the stack.
See Also
xbee_frame_handler_fn()
Todo
Todo Figure out what needs to happen with these frames. Does atcmd layer need to pass errors down to callbacks? Registered endpoints? Tracked conversations?
References be16toh, FAR, payload, and XBEE_UNUSED_PARAMETER.
xbee_wpan_debug int _xbee_wpan_tick (wpan_dev_t * dev)
Simple stub function for the wpan_dev_t object to map the generic `tick wpan_dev_t` call into a `tick xbee_dev_t` call.
Note that this works because the xbee_dev_t structure starts with a wpan_dev_t structure, so the wpan_dev_t address is the same as the xbee_dev_t address.
See wpan_tick_fn() for parameters and return value.
References xbee_dev_tick().
Referenced by xbee_wpan_init().
int xbee_wpan_init (xbee_dev_t * xbee, const wpan_endpoint_table_entry_t * ep_table)
Configure xbee_dev_t for APS-layer (endpoint/cluster) networking.
If using this layer, be sure to call wpan_tick (instead of xbee_dev_tick) so it can manage the APS layers of the network stack.
Parameters
in,out xbee device to configure
in ep_table pointer to an endpoint table to use with device
Return values
0 success
-EINVAL invalid parameter passed to function
References _xbee_endpoint_send(), _xbee_wpan_tick(), EINVAL, wpan_dev_t::endpoint_send, wpan_dev_t::endpoint_table, wpan_dev_t::tick, and xbee_dev_t::wpan_dev.
Variable Documentation
uint8_t options
bitfield, see XBEE_RX_OPT_xxx macros
combination of XBEE_TX_OPT_* macros
xbee_frame_receive_t
Initial value:
{
   uint8_t frame_type
Format of XBee API frame type 0x90 (XBEE_FRAME_RECEIVE); received from XBee by host.
XBEE_FRAME_RECEIVE (0x90)