AT Commands
This layer wraps the AT request/response frames to provide an easy method for querying/setting registers on, and sending AT commands to the XBee.
Files
file xbee_atcmd.c
Code related to sending AT command requests and processing the responses.
file atcmd.h
Sending AT command requests and processing the responses.
file reg_descr.h
Header for XBee register descriptors.
Data Structures
union xbee_at_cmd_t
Datatype used for passing and storing XBee AT Commands.
struct xbee_cmd_response_t
Structure used to pass AT Command responses to registered callback handlers.
struct xbee_cmd_request_t
This structure is used to keep track of outstanding local and remote AT requests.
union xbee_header_at_request_t
Useful typedef to create either a local or remote request frame.
union xbee_frame_at_response_t
Useful typedef for casting either a local or remote response frame.
struct xbee_command_list_context_t
Context data passed to command list processor.
struct xbee_atcmd_reg_t
Entry for table of XBee registers to query at startup.
struct _xbee_reg_descr_t
Macros
#define _xbee_atcmd_debug
#define XBEE_ATCMD_REG_REFRESH_IDX 6
Offset into _xbee_atcmd_query_regs to use when refreshing the xbee_dev_t/ wpan_dev_t structure.
#define XBEE_CMD_REQUEST_TABLESIZE 2
Maximum number of outstanding requests.
#define XBEE_CMD_MAX_PARAM_LENGTH 48
Maximum number of bytes in the parameter sent to a command.
#define XBEE_CMD_REMOTE_TIMEOUT 180
Timeout (in seconds) to wait for a response to a remote command.
#define XBEE_CMD_LOCAL_TIMEOUT 2
Timeout (in seconds) to wait for a response to a local command.
#define XBEE_CMD_ATEO_INSECURE_JOIN (1<<0)
#define XBEE_CMD_ATEO_USE_TRUST_CENTER (1<<1)
#define XBEE_CMD_ATEO_USE_HASH_LINK_KEY (1<<2)
#define XBEE_CMD_ATEO_USE_AUTHENTICATION (1<<3)
#define XBEE_AT_RESP_STATUS(var) ((var) & XBEE_AT_RESP_STATUS_MASK)
Macro for checking the status byte of an AT response.
#define XBEE_ATCMD_REG(c1, c2, type, obj, field)
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_CB(c1, c2, cb, flags) { { { c1, c2 } }, flags, XBEE_CLT_NONE, cb, 0, 0 }
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_MOVE_THEN_CB(c1, c2, type, obj, field, cb, flags)
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_SET_8(c1, c2, value) { { { c1, c2 } }, 0, XBEE_CLT_SET_8, NULL, value, 0 }
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_END { { { '\0', '\0' } } }
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_END_CMD(c1, c2) { { { c1, c2 } }, 0, XBEE_CLT_LAST, NULL, 0, 0 }
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_END_CB(cb, flags) { { { '\0', '\0' } }, flags, XBEE_CLT_NONE, cb, 0, 0 }
Macro used in creating command list tables.
#define XBEE_ATCMD_REG_VALID(ptr) (ptr->command.w != 0)
#define xbee_cmd_list_status(clc) ((clc)->status)
#define XBEE_CMD_REQUEST_EMPTY(index) (xbee_cmd_request_table[index].device == NULL)
Is entry index available (unused)?
#define XBEE_CMD_REQUEST_HANDLE(index) ((index << 8) || xbee_cmd_request_table[index].sequence)
Return the handle for entry index (combination of index and .sequence member of entry).
#define XBEE_FRAME_HANDLE_LOCAL_AT
#define XBEE_FRAME_HANDLE_REMOTE_AT { XBEE_FRAME_REMOTE_AT_RESPONSE, 0, _xbee_cmd_handle_response, NULL }
Typedefs
typedef int(* xbee_cmd_callback_fn)(const xbee_cmd_response_t FAR *response)
Callback registered to an AT Command with xbee_cmd_set_callback().
typedef PACKED_STRUCT xbee_header_local_at_req
Header for AT Commands sent to the local (serially-attached) XBee.
typedef PACKED_STRUCT xbee_header_remote_at_req
Header to AT Commands sent to a remote XBee on the network.
typedef PACKED_STRUCT xbee_header_local_at_resp
typedef PACKED_STRUCT xbee_header_remote_at_resp
typedef PACKED_STRUCT xbee_frame_local_at_resp
Response to an AT Command sent to the local serially-connected XBee.
typedef PACKED_STRUCT xbee_frame_remote_at_resp
Response to an AT Command sent to a remote XBee.
typedef void(* xbee_command_list_fn)(const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
Callback registered for individual command list commands.
Enumerations
enum xbee_at_resp_status {
*
XBEE_AT_RESP_STATUS_MASK = 0x0F,
XBEE_AT_RESP_SUCCESS = 0,
XBEE_AT_RESP_ERROR = 1,
XBEE_AT_RESP_BAD_COMMAND = 2,
*
XBEE_AT_RESP_BAD_PARAMETER = 3,
XBEE_AT_RESP_TX_FAIL = 4,
XBEE_AT_RESP_ATND_RSSI_INVALID = 0x40
 }
Possible values of status byte in xbee_header_local_at_resp_t and xbee_frame_local_at_resp_t.
enum xbee_command_list_status { XBEE_COMMAND_LIST_RUNNING = -EBUSY,
XBEE_COMMAND_LIST_DONE = 0,
XBEE_COMMAND_LIST_TIMEOUT = -ETIMEDOUT,
XBEE_COMMAND_LIST_ERROR = -EIO
 }
Status codes for xbee_cmd_list_status()
enum xbee_command_list_type {
*
XBEE_CLT_NONE,
XBEE_CLT_COPY,
XBEE_CLT_COPY_BE,
XBEE_CLT_SET,
*
XBEE_CLT_SET_STR,
XBEE_CLT_SET_BE,
XBEE_CLT_SET_8,
XBEE_CLT_LAST
 }
enum _xbee_rci_type_t {
*
XBEE_RCI_TYPE_UINT32,
XBEE_RCI_TYPE_HEX32,
XBEE_RCI_TYPE_STRING,
XBEE_RCI_TYPE_BIN,
*
XBEE_RCI_TYPE_ADDR64
 }
iDigi RCI type names used by do_command type=zigbee.
Functions
int xbee_cmd_tick (void)
This function should be called periodically (at least every few seconds) to expire old entries from the AT Command Request table.
xbee_cmd_request_t FAR * _xbee_cmd_handle_to_address (int16_t handle)
int _xbee_cmd_issue_list (xbee_dev_t *xbee, xbee_command_list_context_t FAR *clc, const xbee_cmd_response_t FAR *response)
int _xbee_cmd_list_callback (const xbee_cmd_response_t FAR *response)
int xbee_cmd_list_execute (xbee_dev_t *xbee, xbee_command_list_context_t FAR *clc, const xbee_atcmd_reg_t FAR *list, void FAR *base, const wpan_address_t FAR *address)
Execute a list of AT commands.
enum xbee_command_list_status() xbee_cmd_list_status (xbee_command_list_context_t FAR *clc)
Determine status of command list execution.
int xbee_cmd_init_device (xbee_dev_t *xbee)
Initialize the AT Command layer for an XBee device.
void _xbee_cmd_query_handle_eo (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
void _xbee_cmd_query_handle_ai (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
void _xbee_cmd_query_handle_end (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
int xbee_cmd_query_device (xbee_dev_t *xbee, uint_fast8_t refresh)
Learn about the underlying device by sending a series of commands and storing the results in the xbee_dev_t.
int xbee_cmd_query_status (xbee_dev_t *xbee)
Check the status of querying an XBee device, as initiated by xbee_cmd_query_device().
int16_t xbee_cmd_create (xbee_dev_t *xbee, const char FAR command[3])
Allocate an AT Command request.
int _xbee_cmd_release_request (xbee_cmd_request_t FAR *request)
Release an entry from the request table by marking it as available.
int xbee_cmd_release_handle (int16_t handle)
Release an entry from the request table by marking it as available.
int xbee_cmd_set_command (int16_t handle, const char FAR command[3])
Change the command associated with a request.
int xbee_cmd_set_callback (int16_t handle, xbee_cmd_callback_fn callback, void FAR *context)
Associate a callback with a given AT Command request.
int xbee_cmd_set_target (int16_t handle, const addr64 FAR *ieee, uint16_t network_address)
Associate a remote XBee device with a given AT Command request.
uint8_t _xbee_cmd_encode_param (void FAR *buffer, uint32_t value)
Store an unsigned integer in 1, 2 or 4 bytes as a parameter to an AT command.
int xbee_cmd_set_flags (int16_t handle, uint16_t flags)
Set the flags for a given AT Command request.
int xbee_cmd_clear_flags (int16_t handle, uint16_t flags)
Clear the flags for a given AT Command request.
int xbee_cmd_set_param (int16_t handle, uint32_t value)
Set the parameter (up to 32-bits) for a given AT Command request.
int xbee_cmd_set_param_bytes (int16_t handle, const void FAR *data, uint8_t length)
Set the parameter for a given AT Command request to a sequence of bytes.
int xbee_cmd_set_param_str (int16_t handle, const char FAR *str)
Set a string parameter for a given AT Command request (e.g., the `NI` node identifier command).
int xbee_cmd_send (int16_t handle)
Send an AT Command to a local or remote XBee device.
int _xbee_cmd_handle_response (xbee_dev_t *xbee, const void FAR *rawframe, uint16_t length, void FAR *context)
Callback handler registered for frame types XBEE_FRAME_LOCAL_AT_RESPONSE (0x88) and XBEE_FRAME_REMOTE_AT_RESPONSE (0x97).
int _xbee_cmd_modem_status (xbee_dev_t *xbee, const void FAR *payload, uint16_t length, void FAR *context)
Receive modem status frames and update our network address (and payload size) on state changes.
int xbee_cmd_simple (xbee_dev_t *xbee, const char FAR command[3], uint32_t value)
Simple interface for sending a command with a parameter to the local XBee without checking for a response.
int xbee_cmd_execute (xbee_dev_t *xbee, const char FAR command[3], const void FAR *data, uint8_t length)
Simple interface for sending a command with an optional parameter to the local XBee without checking for a response.
void xbee_identify (xbee_dev_t *xbee, bool_t identify)
Programs with the ZCL Identify Server Cluster can call this function in their main loop to have the XBee module's association LED flash fast (100ms cycle) when in Identify Mode.
Variables
FAR xbee_cmd_request_t xbee_cmd_request_table [XBEE_CMD_REQUEST_TABLESIZE]
Table used to keep track of outstanding requests.
const xbee_atcmd_reg_t _xbee_atcmd_query_regs []
xbee_command_list_context_t _xbee_atcmd_query_regs_head
uint8_t frame_id
1 to 255, or 0 to suppress the Transmit Status response
xbee_at_cmd_t command
two-character AT Command
xbee_header_local_at_req_t
addr64 ieee_address
64-bit IEEE address (big-endian) of target
uint16_t network_address_be
16-bit network address (big-endian) of target
uint8_t options
Options byte (see XBEE_REMOTE_AT_OPT_* macros)
xbee_header_remote_at_req_t
uint8_t status
See enum xbee_at_resp_status.
xbee_header_local_at_resp_t
xbee_header_remote_at_resp_t
uint8_t value [1]
First byte of multi-byte value.
xbee_frame_local_at_resp_t
xbee_frame_remote_at_resp_t
FAR xbee_cmd_request_t xbee_cmd_request_table [XBEE_CMD_REQUEST_TABLESIZE]
Table used to keep track of outstanding requests.
const char * _xbee_rci_types []
Table to map _xbee_rci_type_t to RCI type string.
const FAR _xbee_reg_descr_t _xbee_reg_table []
Return values for xbee_cmd_callback_fn() functions.
#define XBEE_ATCMD_DONE 0
Returned by an xbee_cmd_callback_fn() if the handle can be released.
#define XBEE_ATCMD_REUSE 1
Returned by an xbee_cmd_callback_fn() if more reponses are expected, or it has re-used the command handle.
Values for .options member of xbee_header_remote_at_req_t.
#define XBEE_REMOTE_AT_OPT_QUEUE 0x00
Queue changes until ATAC command or another request with XBEE_REMOTE_AT_OPT_IMMEDIATE set.
#define XBEE_REMOTE_AT_OPT_IMMEDIATE 0x02
Apply changes immediately, don't wait for ATAC command.
Detailed Description
This layer wraps the AT request/response frames to provide an easy method for querying/setting registers on, and sending AT commands to the XBee.
Macro Definition Documentation
#define XBEE_AT_RESP_STATUS(var) ((var) & XBEE_AT_RESP_STATUS_MASK)
Macro for checking the status byte of an AT response.
If this library is compiled without DigiMesh support, we can use a simpler test.
Referenced by _sxa_disc_atnd_response(), and xbee_disc_atnd_response_handler().
#define XBEE_ATCMD_REG(c1, c2, type, obj, field)
Value:
{ { { c1, c2 } }, 0, type, NULL, \
      (uint8_t) sizeof((*(obj *)NULL).field), \
      (uint8_t) offsetof(obj, field) }
Macro used in creating command list tables.
This macro does not set a callback.
Parameters
in c1 first character of AT command
in c2 second character of AT command
in type one of xbee_command_list_type enumerated values: XBEE_CLT_NONE - no action except to issue the command. 'obj' and 'field' parameters are ignored. XBEE_CLT_COPY - copy response data directly XBEE_CLT_COPY_BE - copy numeric data to host byte order XBEE_CLT_SET - set command parameter directly XBEE_CLT_SET_STR - set command parameter as null- terminated string. XBEE_CLT_SET_BE - set numeric command parameter
in obj typedef name of object at base address
in field field in obj in which to store result
Note
The 'type' parameter allows for either setting the data in the base structure as the command parameter (XBEE_CLT_SET*) or the converse, which is copying the command result back to the base structure (XBEE_CLT_COPY*).
Returns
xbee_atcmd_reg_t record for constructing command list tables
See Also
XBEE_ATCMD_REG_CB, XBEE_ATCMD_REG_SET_8
#define XBEE_ATCMD_REG_CB(c1, c2, cb, flags) { { { c1, c2 } }, flags, XBEE_CLT_NONE, cb, 0, 0 }
Macro used in creating command list tables.
Parameters
in c1 first character of AT command
in c2 second character of AT command
in cb callback function (prototype xbee_command_list_fn)
in flags 8-bit flags for callback (arbitrary).
Returns
xbee_atcmd_reg_t record for constructing command list tables
See Also
XBEE_ATCMD_REG
#define XBEE_ATCMD_REG_END { { { '\0', '\0' } } }
Macro used in creating command list tables.
Used to terminate table, with no special final callback. This must be the last entry if used, or XBEE_ATCMD_REG_END_CB must be used.
#define XBEE_ATCMD_REG_END_CB(cb, flags) { { { '\0', '\0' } }, flags, XBEE_CLT_NONE, cb, 0, 0 }
Macro used in creating command list tables.
Used to terminate table, with a final callback. This must be the last entry if used, or XBEE_ATCMD_REG_END must be used.
Parameters
in cb callback function (prototype xbee_command_list_fn).
Note
The 'response' parameter to the callback will be the final command response received.
Parameters
in flags 8-bit flags for callback (arbitrary).
#define XBEE_ATCMD_REG_END_CMD(c1, c2) { { { c1, c2 } }, 0, XBEE_CLT_LAST, NULL, 0, 0 }
Macro used in creating command list tables.
Used to terminate table, with a command (usually ND or WR). This must be the last entry if used.
#define XBEE_ATCMD_REG_MOVE_THEN_CB(c1, c2, type, obj, field, cb, flags)
Value:
{ { { c1, c2 } }, flags, type, cb, \
      (uint8_t) sizeof((*(obj *)NULL).field), \
      (uint8_t) offsetof(obj, field) }
Macro used in creating command list tables.
This is a combination of XBEE_ATCMD_REG (moving data automatically) and XBEE_ATCMD_REG_CB (calling a callback function). The callback function is invoked after the data move.
Parameters
in c1 first character of AT command
in c2 second character of AT command
in type one of xbee_command_list_type enumerated values: XBEE_CLT_NONE - no action except to issue the command. 'obj' and 'field' parameters are ignored. XBEE_CLT_COPY - copy response data directly XBEE_CLT_COPY_BE - copy numeric data to host byte order XBEE_CLT_SET - set command parameter directly XBEE_CLT_SET_STR - set command parameter as null- terminated string. XBEE_CLT_SET_BE - set numeric command parameter
in obj typedef name of object at base address
in field field in obj in which to store result
in cb callback function (prototype xbee_command_list_fn)
in flags 8-bit flags for callback (arbitrary).
Returns
xbee_atcmd_reg_t record for constructing command list tables
See Also
XBEE_ATCMD_REG, XBEE_ATCMD_REG_CB
#define XBEE_ATCMD_REG_REFRESH_IDX 6
Offset into _xbee_atcmd_query_regs to use when refreshing the xbee_dev_t/ wpan_dev_t structure.
Referenced by xbee_cmd_query_device().
#define XBEE_ATCMD_REG_SET_8(c1, c2, value) { { { c1, c2 } }, 0, XBEE_CLT_SET_8, NULL, value, 0 }
Macro used in creating command list tables.
This macro does not set a callback.
Parameters
in c1 first character of AT command
in c2 second character of AT command
in value unsigned 8-bit value (compile-time constant) to set.
Returns
xbee_atcmd_reg_t record for constructing command list tables
See Also
XBEE_ATCMD_REG
#define XBEE_ATCMD_REUSE 1
Returned by an xbee_cmd_callback_fn() if more reponses are expected, or it has re-used the command handle.
Referenced by _xbee_cmd_handle_response(), _xbee_cmd_list_callback(), and xbee_cmd_tick().
#define XBEE_CMD_MAX_PARAM_LENGTH 48
Maximum number of bytes in the parameter sent to a command.
The NI command takes a 20-byte string. ATZT is 48 bytes, ATZU is 22. Platforms can override this when limiting to AT commands with shorter parameters (e.g., 16 bytes when not using the certificate parameters).
Referenced by xbee_cmd_set_param_bytes(), and xbee_cmd_set_param_str().
#define XBEE_CMD_REMOTE_TIMEOUT 180
Timeout (in seconds) to wait for a response to a remote command.
Set to a high value to allow for a sleeping end device.
Referenced by xbee_cmd_send().
#define XBEE_CMD_REQUEST_HANDLE(index) ((index << 8) || xbee_cmd_request_table[index].sequence)
Return the handle for entry index (combination of index and .sequence member of entry).
#define XBEE_CMD_REQUEST_TABLESIZE 2
Maximum number of outstanding requests.
Two should be sufficient in most (all?) cases. One might even be enough if space is tight.
Referenced by _xbee_cmd_handle_response(), _xbee_cmd_handle_to_address(), xbee_cmd_create(), and xbee_cmd_tick().
#define XBEE_FRAME_HANDLE_LOCAL_AT
Value:
{ XBEE_FRAME_LOCAL_AT_RESPONSE, 0,
      _xbee_cmd_handle_response, NULL }, \
   { XBEE_FRAME_MODEM_STATUS, 0, _xbee_cmd_modem_status
      , NULL }
#define XBEE_REMOTE_AT_OPT_QUEUE 0x00
Queue changes until ATAC command or another request with XBEE_REMOTE_AT_OPT_IMMEDIATE set.
Referenced by xbee_cmd_send().
Typedef Documentation
typedef int(* xbee_cmd_callback_fn)(const xbee_cmd_response_t FAR *response)
Callback registered to an AT Command with xbee_cmd_set_callback().
It should not modify the contents of the xbee_cmd_response_t structure passed to it. It should return either XBEE_ATCMD_DONE or XBEE_ATCMD_REUSE.
View the help on xbee_cmd_response_t for details on the members of that structure.
Parameters
in response response received for AT Command
Return values
XBEE_ATCMD_DONE done with the request handle
XBEE_ATCMD_REUSE more responses are expected, or the request handle will be reused
See Also
xbee_cmd_set_callback(), xbee_cmd_response_t
typedef void(* xbee_command_list_fn)(const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
Callback registered for individual command list commands.
Parameters
in response response received for AT Command. From this, the context field points to the start of the entire set of commands in the list being processed.
in reg Table element for this command. Usually, the callback will dereference reg->context to find any required auxiliary data for processing this command.
in,out base Base address of structure to populate with response value (typical use).
Note
This callback is called for a command response, and is intended to be used for manipulating the raw response data into something suitable for the application. There is no corresponding callback for a request (i.e. called before setting parameter data); the application is expected to perform setting parameter manipulation before invoking xbee_cmd_list_execute().
typedef PACKED_STRUCT xbee_frame_local_at_resp
Initial value:
{
   xbee_header_local_at_resp_t header
Response to an AT Command sent to the local serially-connected XBee.
typedef PACKED_STRUCT xbee_frame_remote_at_resp
Initial value:
{
   xbee_header_remote_at_resp_t header
Response to an AT Command sent to a remote XBee.
typedef PACKED_STRUCT xbee_header_local_at_req
Initial value:
{
   
   uint8_t frame_type
Header for AT Commands sent to the local (serially-attached) XBee.
typedef PACKED_STRUCT xbee_header_local_at_resp
Initial value:
{
   
   uint8_t frame_type
typedef PACKED_STRUCT xbee_header_remote_at_req
Initial value:
{
   
   uint8_t frame_type
Header to AT Commands sent to a remote XBee on the network.
typedef PACKED_STRUCT xbee_header_remote_at_resp
Initial value:
{
   
   uint8_t frame_type
Enumeration Type Documentation
enum _xbee_rci_type_t
iDigi RCI type names used by do_command type=zigbee.
This table is used so as to avoid having XBEE_RCI_TYPE_STRING pointers in the register descriptor table.
enum xbee_at_resp_status
Possible values of status byte in xbee_header_local_at_resp_t and xbee_frame_local_at_resp_t.
Enumerator:
XBEE_AT_RESP_STATUS_MASK
 Mask to ignore extra bits used in the status response.
XBEE_AT_RESP_ATND_RSSI_INVALID
 The RSSI field of the ATND response is not valid [DigiMesh].
enum xbee_command_list_status
Status codes for xbee_cmd_list_status()
We force these to be -Exxx codes (or 0).
enum xbee_command_list_type
Enumerator:
XBEE_CLT_NONE
 No default action. Often used for callbacks.
XBEE_CLT_COPY
 Copy response data byte-for-byte to base struct.
XBEE_CLT_COPY_BE
 Copy response, changing expected big-endian to host byte order, and store in base struct. Data must be 1,2 or 4 bytes, assumed unsigned.
XBEE_CLT_SET
 Use data in base struct as parameter for command, with binary data copied byte-for-byte.
XBEE_CLT_SET_STR
 Use data in base struct as parameter for command, with null-terminated string data copied byte-for-byte.
XBEE_CLT_SET_BE
 Use data in base struct as parameter for command, changing host byte order to big-endian. Data must be 1,2 or 4 bytes, assumed unsigned.
XBEE_CLT_SET_8
 Set value to immediate 8-bit constant in .bytes field of the xbee_atcmd_reg_t entry. No response.
XBEE_CLT_LAST
 Last command, any response is discarded, no further command list entries are processed. This is useful if ND is the last command, since the command list will terminate, but discovered nodes will be handled subsequently (asynchronously).
Function Documentation
uint8_t _xbee_cmd_encode_param (void FAR * buffer, uint32_t value)
Store an unsigned integer in 1, 2 or 4 bytes as a parameter to an AT command.
Parameters
in buffer buffer to store value
in value value to store
Returns
Number of bytes required (1, 2 or 4) to hold value.
References FAR, htobe16, htobe32, and value.
Referenced by xbee_cmd_set_param(), and xbee_cmd_simple().
int _xbee_cmd_handle_response (xbee_dev_t * xbee, const void FAR * rawframe, uint16_t length, void FAR * context)
Callback handler registered for frame types XBEE_FRAME_LOCAL_AT_RESPONSE (0x88) and XBEE_FRAME_REMOTE_AT_RESPONSE (0x97).
Should only be called by the frame dispatcher and unit tests.
See the function help for xbee_frame_handler_fn() for full documentation on this function's API.
References _xbee_cmd_release_request(), be16toh, be32toh, xbee_cmd_response_t::command, command, xbee_cmd_response_t::context, xbee_cmd_response_t::device, EINVAL, FAR, xbee_cmd_response_t::flags, frame_id, xbee_dev_t::frame_id, xbee_cmd_response_t::handle, PRIpFAR, xbee_cmd_response_t::source, status, xbee_cmd_response_t::value, value, xbee_cmd_response_t::value_bytes, xbee_cmd_response_t::value_length, XBEE_ATCMD_REUSE, XBEE_CMD_FLAG_REMOTE, xbee_cmd_request_table, XBEE_CMD_REQUEST_TABLESIZE, XBEE_FRAME_LOCAL_AT_RESPONSE, XBEE_FRAME_REMOTE_AT_RESPONSE, XBEE_SET_TIMEOUT_SEC, and XBEE_UNUSED_PARAMETER.
xbee_cmd_request_t FAR * _xbee_cmd_handle_to_address (int16_t handle)
Convert a handle (16-bit int) to a pointer into the command request table. Ensures that the handle is valid (correct index and sequence bytes).
Parameters
in handle Handle returned from xbee_cmd_create().
Returns
Pointer into the request table or NULL if handle is invalid.
See Also
xbee_cmd_create()
References FAR, xbee_cmd_request_table, and XBEE_CMD_REQUEST_TABLESIZE.
Referenced by xbee_cmd_clear_flags(), xbee_cmd_release_handle(), xbee_cmd_send(), xbee_cmd_set_callback(), xbee_cmd_set_command(), xbee_cmd_set_flags(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), and xbee_cmd_set_target().
int _xbee_cmd_issue_list (xbee_dev_t * xbee, xbee_command_list_context_t FAR * clc, const xbee_cmd_response_t FAR * response)
Helper function to send off the next command in the list.
References FAR, XBEE_CLT_SET, XBEE_CLT_SET_8, XBEE_CLT_SET_BE, XBEE_CLT_SET_STR, xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), and xbee_cmd_set_param_str().
Referenced by _xbee_cmd_list_callback(), and xbee_cmd_list_execute().
int _xbee_cmd_list_callback (const xbee_cmd_response_t FAR * response)
Callback used by xbee_cmd_query_device (and possibly other functions) to learn about the attached XBee device (hardware/firmware version, address, etc.)
View function help for xbee_cmd_set_callback() for details on xbee_cmd_response_t structure.
This callback should only be called by xbee_cmd_handle_response(). ***
References _xbee_cmd_issue_list(), command, FAR, PRIsFAR, PRIX32, XBEE_ATCMD_DONE, XBEE_ATCMD_REUSE, XBEE_CLT_COPY, XBEE_CLT_COPY_BE, XBEE_CLT_LAST, xbee_cmd_release_handle(), and xbee_cmd_send().
Referenced by xbee_cmd_list_execute().
int _xbee_cmd_modem_status (xbee_dev_t * xbee, const void FAR * payload, uint16_t length, void FAR * context)
Receive modem status frames and update our network address (and payload size) on state changes.
See Also
xbee_frame_handler_fn()
References EINVAL, FAR, xbee_dev_t::flags, status, xbee_cmd_query_device(), XBEE_MODEM_STATUS_COORD_START, XBEE_MODEM_STATUS_JOINED, XBEE_MODEM_STATUS_KEY_ESTABLISHED, and XBEE_UNUSED_PARAMETER.
int _xbee_cmd_release_request (xbee_cmd_request_t FAR * request)
Release an entry from the request table by marking it as available.
For internal driver use only -- userspace code should use xbee_cmd_release_handle() instead.
Parameters
in request Address of the table entry.
Return values
0 request freed
-EINVAL address (request) is not valid
See Also
xbee_cmd_create(), xbee_cmd_release_handle()
Todo
Todo add bounds checking on request to make sure it's in the table?
References EINVAL.
Referenced by _xbee_cmd_handle_response(), xbee_cmd_release_handle(), xbee_cmd_send(), and xbee_cmd_tick().
int xbee_cmd_clear_flags (int16_t handle, uint16_t flags)
Clear the flags for a given AT Command request.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in flags One or more of the following:
XBEE_CMD_FLAG_QUEUE_CHANGE don't apply changes until ATAC or another command without this flag is sent
Return values
0 flags cleared
-EINVAL handle is not valid
See Also
xbee_cmd_set_flags
References _xbee_cmd_handle_to_address(), EINVAL, FAR, and XBEE_CMD_FLAG_USER_MASK.
int16_t xbee_cmd_create (xbee_dev_t * xbee, const char FAR command[3])
Allocate an AT Command request.
Parameters
in xbee XBee device to use as the target (local) or to send through (remote). This function will automatically call xbee_cmd_init() if it hasn't already been called for this device.
in command Two-letter AT Command to send (e.g., `VR`, `NI`, etc.).
Return values
>0 a `handle` to a request that can be built up and sent to a local (serially-attached) or remote XBee module.
-ENOSPC the AT command table is full (increase the compile-time macro XBEE_CMD_REQUEST_TABLESIZE)
-EINVAL an invalid parameter was passed to the function
See Also
xbee_cmd_init_device(), xbee_cmd_query_device(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References EINVAL, ENOSPC, FAR, xbee_dev_t::flags, xbee_cmd_init_device(), xbee_cmd_request_table, XBEE_CMD_REQUEST_TABLESIZE, xbee_cmd_tick(), XBEE_DEV_FLAG_CMD_INIT, and XBEE_SET_TIMEOUT_SEC.
Referenced by _xbee_cmd_issue_list(), xbee_io_configure(), xbee_io_set_digital_output(), and xbee_io_set_options().
int xbee_cmd_execute (xbee_dev_t * xbee, const char FAR command[3], const void FAR * data, uint8_t length)
Simple interface for sending a command with an optional parameter to the local XBee without checking for a response.
For an asynchronous method of sending AT commands and getting the response, see xbee_cmd_create, the xbee_cmd_set_* functions and xbee_cmd_send.
Parameters
in xbee XBee device to use as the target.
in command Two-letter AT Command to send (e.g., `ID`, `CH`, etc.).
in data Optional big-endian (MSB-first) value to assign to command. Use NULL if command doesn't take a parameter.
in length Number of bytes in data; ignored if data is NULL.
Return values
0 command sent
-EINVAL an invalid parameter was passed to the function
-EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal).
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_simple()
References FAR, XBEE_FRAME_LOCAL_AT_CMD, xbee_frame_write(), and xbee_next_frame_id().
Referenced by xbee_disc_discover_nodes().
int xbee_cmd_init_device (xbee_dev_t * xbee)
Initialize the AT Command layer for an XBee device.
You need to call this function before any of the other xbee_cmd_* functions.
Parameters
in xbee XBee device on which to enable the AT Command layer. This function will automatically call xbee_cmd_query_device if it hasn't already been called for this device.
Return values
0 the XBee device was successfully configured to send and receive AT commands
-EINVAL an invalid parameter was passed to the function
See Also
xbee_cmd_query_device(), xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References EINVAL, xbee_dev_t::flags, xbee_cmd_query_device(), XBEE_DEV_FLAG_CMD_INIT, and XBEE_DEV_FLAG_QUERY_BEGIN.
Referenced by xbee_cmd_create().
int xbee_cmd_list_execute (xbee_dev_t * xbee, xbee_command_list_context_t FAR * clc, const xbee_atcmd_reg_t FAR * list, void FAR * base, const wpan_address_t FAR * address)
Execute a list of AT commands.
Parameters
in,out xbee Device to execute commands
out clc List head to set up. This must be static since callback functions access it asynchronously.
in list First entry of list of commands to execute. The list must be terminated by either XBEE_ATCMD_REG_END or XBEE_ATCMD_REG_END_CB. List entries are created using XBEE_ATCMD_REG macros etc.
in base Base address of a structure to fill in with command results or as a source of values to set.
in address Remote address, or NULL if local device.
Return values
0 started sending commands from the list
-ENOSPC the AT command table is full (increase the compile-time macro XBEE_CMD_REQUEST_TABLESIZE)
-EINVAL an invalid parameter was passed to the function
See Also
xbee_cmd_list_status()
References _xbee_cmd_issue_list(), _xbee_cmd_list_callback(), xbee_cmd_send(), xbee_cmd_set_callback(), and xbee_cmd_set_target().
Referenced by xbee_cmd_query_device().
enum xbee_command_list_status() xbee_cmd_list_status (xbee_command_list_context_t FAR * clc)
Determine status of command list execution.
Parameters
in clc List head passed to xbee_cmd_list_execute().
Return values
XBEE_COMMAND_LIST_RUNNING currently executing commands
XBEE_COMMAND_LIST_DONE successfully completed
XBEE_COMMAND_LIST_TIMEOUT timed out
XBEE_COMMAND_LIST_ERROR completed with error(s)
See Also
xbee_cmd_list_execute()
Referenced by xbee_cmd_query_status(), and xbee_io_query_status().
int xbee_cmd_query_device (xbee_dev_t * xbee, uint_fast8_t refresh)
Learn about the underlying device by sending a series of commands and storing the results in the xbee_dev_t.
This function will likely get called by the XBee stack at some point in the startup/initialization phase.
Use xbee_cmd_query_status() to check on the progress of querying the device.
Parameters
in,out xbee XBee device to query.
in refresh if non-zero, just refresh the volatile values (e.g., network settings, as opposed to device serial number)
Return values
0 Started querying device.
-EBUSY Transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal).
See Also
xbee_cmd_init_device(), xbee_cmd_query_status()
References EINVAL, xbee_dev_t::flags, XBEE_ATCMD_REG_REFRESH_IDX, xbee_cmd_list_execute(), XBEE_DEV_FLAG_QUERY_BEGIN, XBEE_DEV_FLAG_QUERY_DONE, XBEE_DEV_FLAG_QUERY_ERROR, XBEE_DEV_FLAG_QUERY_INPROGRESS, and XBEE_DEV_FLAG_QUERY_REFRESH.
Referenced by _xbee_cmd_modem_status(), xbee_cmd_init_device(), and xbee_cmd_tick().
int xbee_cmd_query_status (xbee_dev_t * xbee)
Check the status of querying an XBee device, as initiated by xbee_cmd_query_device().
Parameters
in xbee device to check
Return values
0 query completed
-EINVAL xbee is NULL
-EBUSY query underway
-ETIMEDOUT query timed out
-EIO halted, but query may not have completed (unexpected response)
References EINVAL, xbee_cmd_list_status(), and xbee_cmd_tick().
int xbee_cmd_release_handle (int16_t handle)
Release an entry from the request table by marking it as available.
Parameters
in handle handle to the request (as returned by xbee_cmd_create)
Return values
0 request freed
-EINVAL handle is not valid
See Also
xbee_cmd_create(), xbee_cmd_release_handle()
References _xbee_cmd_handle_to_address(), and _xbee_cmd_release_request().
Referenced by _xbee_cmd_list_callback().
int xbee_cmd_send (int16_t handle)
Send an AT Command to a local or remote XBee device.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
Return values
0 frame sent
-EINVAL handle is not valid
-EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal).
Note
If the request does not have a callback set, it will be automatically released if xbee_cmd_send() returns 0.
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str()
References _xbee_cmd_handle_to_address(), _xbee_cmd_release_request(), EINVAL, FAR, xbee_header_at_request_t::frame_type, hex_dump(), HEX_DUMP_FLAG_TAB, htobe16, xbee_header_at_request_t::local, xbee_header_at_request_t::remote, XBEE_CMD_FLAG_QUEUE_CHANGE, XBEE_CMD_FLAG_REMOTE, XBEE_CMD_FLAG_REUSE_HANDLE, XBEE_CMD_LOCAL_TIMEOUT, XBEE_CMD_REMOTE_TIMEOUT, XBEE_FRAME_LOCAL_AT_CMD, XBEE_FRAME_LOCAL_AT_CMD_Q, XBEE_FRAME_REMOTE_AT_CMD, xbee_frame_write(), xbee_next_frame_id(), XBEE_REMOTE_AT_OPT_IMMEDIATE, XBEE_REMOTE_AT_OPT_QUEUE, and XBEE_SET_TIMEOUT_SEC.
Referenced by _xbee_cmd_list_callback(), xbee_cmd_list_execute(), xbee_io_configure(), xbee_io_set_digital_output(), and xbee_io_set_options().
int xbee_cmd_set_callback (int16_t handle, xbee_cmd_callback_fn callback, void FAR * context)
Associate a callback with a given AT Command request.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in callback Callback function to receive the AT Command response. This function should take a single parameter (pointer to an xbee_cmd_response_t) and return either XBEE_ATCMD_DONE (if done with the request handle) or XBEE_ATCMD_REUSE (if more responses are expected, or the request handle is going to be reused).
int atcmd_callback(const xbee_cmd_response_t FAR *
      response)
in context Context (or `userdata`) value to pass to the callback along with the AT Command response when it arrives. Should be set to NULL if not used.
Return values
0 callback set
-EINVAL handle is not valid
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address(), EINVAL, and FAR.
Referenced by xbee_cmd_list_execute().
int xbee_cmd_set_command (int16_t handle, const char FAR command[3])
Change the command associated with a request.
Parameters
in handle handle to the request, as returned by xbee_cmd_create()
in command two-letter AT Command to send (e.g., `VR`, `NI`, etc.)
Return values
0 command changed
-EINVAL handle is not valid
See Also
xbee_cmd_create(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address(), EINVAL, and FAR.
Referenced by _xbee_cmd_issue_list().
int xbee_cmd_set_flags (int16_t handle, uint16_t flags)
Set the flags for a given AT Command request.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in flags One or more of the following:
XBEE_CMD_FLAG_QUEUE_CHANGE don't apply changes until ATAC or another command without this flag is sent
Return values
0 flags set
-EINVAL handle is not valid
See Also
xbee_cmd_clear_flags
References _xbee_cmd_handle_to_address(), EINVAL, FAR, and XBEE_CMD_FLAG_USER_MASK.
int xbee_cmd_set_param (int16_t handle, uint32_t value)
Set the parameter (up to 32-bits) for a given AT Command request.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in value Value to use as the parameter to the AT Command. For negative values, or values > 0xFFFFFFFF, use xbee_cmd_set_param_bytes(). For string parameters (e.g., for the `NI` command), use xbee_cmd_set_param_str().
Return values
0 parameter set
-EINVAL handle is not valid
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_encode_param(), _xbee_cmd_handle_to_address(), EINVAL, and FAR.
Referenced by _xbee_cmd_issue_list(), xbee_io_configure(), xbee_io_set_digital_output(), and xbee_io_set_options().
int xbee_cmd_set_param_bytes (int16_t handle, const void FAR * data, uint8_t length)
Set the parameter for a given AT Command request to a sequence of bytes.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in data Pointer to bytes (MSB-first) to copy into request.
in length Number of bytes to copy. 0 < length <= XBEE_CMD_MAX_PARAM_LENGTH
Return values
0 parameter set
-EINVAL handle or length is not valid
-EMSGSIZE length is greater than XBEE_CMD_MAX_PARAM_LENGTH
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address(), EINVAL, EMSGSIZE, FAR, length, and XBEE_CMD_MAX_PARAM_LENGTH.
Referenced by _xbee_cmd_issue_list(), and xbee_cmd_set_param_str().
int xbee_cmd_set_param_str (int16_t handle, const char FAR * str)
Set a string parameter for a given AT Command request (e.g., the `NI` node identifier command).
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in str String to use as the parameter. Must be less than XBEE_CMD_MAX_PARAM_LENGTH characters long.
Return values
0 parameter set
-EINVAL handle is not valid
-EMSGSIZE str is more than XBEE_CMD_MAX_PARAM_LENGTH characters.
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_send()
References EMSGSIZE, length, XBEE_CMD_MAX_PARAM_LENGTH, and xbee_cmd_set_param_bytes().
Referenced by _xbee_cmd_issue_list().
int xbee_cmd_set_target (int16_t handle, const addr64 FAR * ieee, uint16_t network_address)
Associate a remote XBee device with a given AT Command request.
By default, xbee_cmd_create() configures the request as a local AT Command for the serially-attached XBee module. Use this function to send the command to a remote device.
Parameters
in handle Handle to the request, as returned by xbee_cmd_create().
in ieee Pointer to 64-bit IEEE hardware address of target, or NULL to switch back to the local XBee device.
WPAN_IEEE_ADDR_BROADCAST for broadcast.
WPAN_IEEE_ADDR_COORDINATOR for the coordinator (use WPAN_NET_ADDR_UNDEFINED for the network address).
WPAN_IEEE_ADDR_UNDEFINED to use the 16-bit network address.
in network 16-bit network address of target.
WPAN_NET_ADDR_UNDEFINED if the node's network address isn't known or this is a DigiMesh network.
WPAN_NET_ADDR_COORDINATOR for the coordinator (use the coordinator's actual IEEE address for the ieee parameter).
WPAN_NET_ADDR_BCAST_NOT_ASLEEP to broadcast to all nodes that aren't sleeping.
WPAN_NET_ADDR_BCAST_ROUTERS to broadcast to the coordinator and all routers.
Return values
0 target set
-EINVAL handle is not valid
-ENOSYS function not implemented (XBEE_CMD_DISABLE_REMOTE defined)
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_send()
References _xbee_cmd_handle_to_address(), EINVAL, ENOSYS, FAR, and XBEE_CMD_FLAG_REMOTE.
Referenced by xbee_cmd_list_execute(), xbee_io_configure(), xbee_io_set_digital_output(), and xbee_io_set_options().
int xbee_cmd_simple (xbee_dev_t * xbee, const char FAR command[3], uint32_t value)
Simple interface for sending a command with a parameter to the local XBee without checking for a response.
Parameters
in xbee XBee device to use as the target.
in command Two-letter AT Command to send (e.g., `ID`, `CH`, etc.).
in value Value to use as the parameter to the AT Command.
Return values
0 command sent
-EINVAL an invalid parameter was passed to the function
-EBUSY transmit serial buffer is full, or XBee is not accepting serial data (deasserting /CTS signal).
See Also
xbee_cmd_create(), xbee_cmd_set_command(), xbee_cmd_set_callback(), xbee_cmd_set_target(), xbee_cmd_set_param(), xbee_cmd_set_param_bytes(), xbee_cmd_set_param_str(), xbee_cmd_execute()
References _xbee_cmd_encode_param(), FAR, PACKED_STRUCT, PRIu32, PRIx32, XBEE_FRAME_LOCAL_AT_CMD, and xbee_frame_write().
Referenced by xbee_identify().
int xbee_cmd_tick (void)
This function should be called periodically (at least every few seconds) to expire old entries from the AT Command Request table.
Returns
>0 number of requests expired
0 none of the requests in the table expired
References _xbee_cmd_release_request(), xbee_cmd_response_t::command, xbee_cmd_response_t::context, xbee_cmd_response_t::device, FAR, xbee_cmd_response_t::flags, xbee_dev_t::flags, xbee_cmd_response_t::handle, PRIpFAR, XBEE_ATCMD_DONE, XBEE_ATCMD_REUSE, XBEE_CHECK_TIMEOUT_SEC, xbee_cmd_query_device(), xbee_cmd_request_table, XBEE_CMD_REQUEST_TABLESIZE, and XBEE_DEV_FLAG_QUERY_REFRESH.
Referenced by xbee_cmd_create(), xbee_cmd_query_status(), and xbee_io_query_status().
void xbee_identify (xbee_dev_t * xbee, bool_t identify)
Programs with the ZCL Identify Server Cluster can call this function in their main loop to have the XBee module's association LED flash fast (100ms cycle) when in Identify Mode.
Parameters
in xbee device to identify
in identify TRUE if XBee should be in identify mode
See Also
xbee_zcl_identify, zcl_identify_isactive, ZCL_CLUST_ENTRY_IDENTIFY_SERVER
References xbee_cmd_simple().
Variable Documentation
const xbee_atcmd_reg_t _xbee_atcmd_query_regs[]
Initial value:
= {
   XBEE_ATCMD_REG('H', 'V', XBEE_CLT_COPY_BE,
      xbee_dev_t, hardware_version),
   XBEE_ATCMD_REG('V', 'R', XBEE_CLT_COPY_BE,
      xbee_dev_t, firmware_version),
   XBEE_ATCMD_REG('S', 'H', XBEE_CLT_COPY,
      xbee_dev_t, wpan_dev.address.ieee.l[0]),
   XBEE_ATCMD_REG('S', 'L', XBEE_CLT_COPY,
      xbee_dev_t, wpan_dev.address.ieee.l[1]),
   XBEE_ATCMD_REG_CB('E', 'O', _xbee_cmd_query_handle_eo, 0),
   XBEE_ATCMD_REG_CB('A', 'I', _xbee_cmd_query_handle_ai, 0),
   
   XBEE_ATCMD_REG('N', 'P', XBEE_CLT_COPY_BE,
      xbee_dev_t, wpan_dev.payload),
   XBEE_ATCMD_REG('M', 'Y', XBEE_CLT_COPY_BE,
      xbee_dev_t, wpan_dev.address.network),
}
List of XBee registers to query at startup; used to learn about the attached XBee module.
uint8_t command
two-character AT Command
Command from original request.
Referenced by _xbee_cmd_handle_response(), _xbee_cmd_list_callback(), zcl_command_build(), and zcl_default_response().
uint8_t frame_id
1 to 255, or 0 to suppress the Transmit Status response
ID from request, used to match response to request.
Referenced by _xbee_cmd_handle_response().
addr64 ieee_address
64-bit IEEE address (big-endian) of target
64-bit IEEE address (big-endian) of source.
64-bit IEEE address (big-endian) of responder.
uint16_t network_address_be
16-bit network address (big-endian) of target
16-bit network address (big-endian) of source.
16-bit network address (big-endian) of responder.
uint8_t options
Options byte (see XBEE_REMOTE_AT_OPT_* macros)
combination of XBEE_TX_OPT_* macros
bitfield, see XBEE_RX_OPT_xxx macros
Referenced by xbee_ota_server_cmd().
uint8_t status
See enum xbee_at_resp_status.
Note that DigiMesh uses the upper nibble for additional flags -- use XBEE_AT_RESP_STATUS() macro when comparing this field to the xbee_at_resp_status enum.
Referenced by _xbee_cmd_handle_response(), _xbee_cmd_modem_status(), _zcl_onoff_handler(), _zcl_write_attributes(), xbee_ser_get_cts(), xbee_ser_set_rts(), zcl_comm_response(), zcl_default_response(), zcl_encode_attribute_value(), and zcl_invalid_command().
uint8_t value
First byte of multi-byte value.
variable length, only if ZCL_STATUS_SUCCESS
Cached value.
Referenced by _sxa_disc_atnd_response(), _xbee_cmd_encode_param(), _xbee_cmd_handle_response(), _zcl_comm_startup_control_set(), xbee_disc_atnd_response_handler(), zcl_check_minmax(), zcl_print_array_value(), zcl_print_attribute_value(), and zcl_print_struct_value().