SXA
Files
file xbee_sxa_socket.c
Simple XBee API, TCP sockets over ZigBee.
file xbee_reg_descr.c
Code related to the register descriptor table.
file xbee_sxa.c
Simple XBee API.
file sxa.h
Header for Simplified XBee API.
file sxa_socket.h
Header for Simplified XBee API TCP sockets over ZigBee.
Data Structures
struct sxa_cached_group_t
Cached register group value.
struct sxa_node_t
This structure and the attendant functions provide a useful layer for Rabbit applications who wish to use a simplified interface to the XBee API.
struct _sxa_sock_hdr_t
Macros
#define sxa_list_head() sxa_table
#define sxa_list_count() sxa_table_count
#define _XRT_ENTRY(state, tag, at, cxv, desc, units, min, max, rci_type, sxa_field, group)
#define F8 0x0002
#define EZ 0x0004
#define ZB 0x0408
#define X9 0x0010
#define X2 0x0020
#define X8 0x0040
#define DP 0x0080
#define FZ 0x0001
#define SE 0x0100
#define ALL 0x07ff
#define GW 0x8000
#define _xbee_sxa_debug
#define _sys_calloc(s) calloc(s, 1)
#define _sys_malloc(s) malloc(s)
#define _sys_free(p) free(p)
#define SXA_OFFSET(base, ofs) (void FAR *)((char FAR *)(base) + (ofs))
#define _SXA_CG_INIT(id, field, get, fn) { id, offsetof(sxa_node_t, field), get, fn }
#define _SXA_CG_INIT_END { 0, 0, NULL, NULL }
#define _SXA_CACHED_PREFIX_SIZE (sizeof(sxa_cache_flags_t))
#define _SXA_CACHED_STRING(name, len) PACKED_STRUCT { sxa_cache_flags_t flags; uint8_t value[len+1]; } name
Cached string register value.
#define _SXA_CACHED_BIN(name, len) PACKED_STRUCT { sxa_cache_flags_t flags; uint8_t value[len]; } name
Cached binary register value.
#define ZB_CAP_ADV_ADDR 0x00000001
#define ZB_CAP_ZDO 0x00000002
#define ZB_CAP_REMOTE_DDO 0x00000004
#define ZB_CAP_GW_FW 0x00000008
#define ZB_CAP_REMOTE_FW 0x00000010
#define ZB_CAP_ZIGBEE 0x00000020
#define ZB_CAP_ZBPRO 0x00000040
#define ZB_CAP_DIGIMESH 0x00000080
#define ZB_CAP_CHILDREN 0x00000100
#define ZB_CAP_SE 0x00000200
#define sxa_xbee(s) ((s)->xbee)
#define sxa_wpan_address(s) ((s)->addr_ptr)
#define XBEE_FRAME_HANDLE_ND_RESPONSE
Macro for registering a handler to receive node announcements via both ATND responses and 0x95 frames received.
#define XBEE_DISC_CLIENT_CLUST_ENTRY
#define XBEE_FRAME_HANDLE_IS_RESPONSE
Macro for registering a handler to receive I/O samples via both ATIS responses and 0x92 frames received.
#define XBEE_IO_CLIENT_CLUST_ENTRY
#define SXA_SOCKET_MTU 104
Network interface Maximum Transmission Unit, as seen by TCP stack.
#define SXA_INDEX_TO_IP(index) IPADDR(127,1,0,index)
Macro to generate the appropriate `loopback` IP address, i.e.
#define SXA_STREAM_PORT UINT16_C(61616)
Macro to use for first and last valid TCP port numbers, for both source port and destination port.
#define SXA_MAX_STREAM_PORT UINT16_C(61616+255)
#define WPAN_ENDPOINT_DIGI_STREAM 0x66
Provisional endpoint for reliable stream.
#define SXA_SOCKET_ENDPOINT
Place this entry in endpoint table to enable SXA sockets.
Typedefs
typedef void(* sxa_cache_upd_fn)(struct sxa_node_t FAR *sxa, const struct sxa_cached_group_t FAR *cgroup)
Function registered for cache group update post-processing.
Enumerations
enum {
*
_SXA_CACHED_UNKNOWN = 0x00,
_SXA_CACHED_OK = 0x01,
_SXA_CACHED_ERROR = 0x02,
_SXA_CACHED_BUSY = 0x04,
*
_SXA_CACHED_PENDING = 0x08,
_SXA_CACHED_BAD_GROUP = 0x10
 }
enum {
*
SXA_CACHED_NONE,
SXA_CACHED_NODE_ID,
SXA_CACHED_IO_CONFIG,
SXA_CACHED_DEVICE_INFO,
*
SXA_CACHED_DHDL,
SXA_CACHED_MISC = 255
 }
This enum gives numeric identification to all cache groups.
Functions
_xbee_sxa_debug int _sxa_socket_tx_handler (struct LoopbackHandler __far *lh, ll_Gather *g)
int _sxa_socket_rx_handler (const wpan_envelope_t FAR *envelope, wpan_ep_state_t FAR *ep_state)
_xbee_sxa_debug int sxa_socket_init (void)
_xbee_sxa_debug sxa_node_t FAR *() sxa_list_head (void)
_xbee_sxa_debug int() sxa_list_count (void)
_xbee_sxa_debug xbee_dev_t *() sxa_xbee (sxa_node_t FAR *sxa)
_xbee_sxa_debug wpan_address_t
*
FAR *() sxa_wpan_address (sxa_node_t FAR *sxa)
const sxa_cached_group_t FAR * _sxa_cache_group_by_id (uint16_t id)
void _sxa_process_version_info (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
void _sxa_update_io_config_group (sxa_node_t FAR *sxa, const sxa_cached_group_t FAR *cgroup)
_xbee_sxa_debug int _sxa_disc_process_node_data (xbee_dev_t *xbee, const void FAR *raw, int length)
Function shared by multiple functions that process Node Identification Messages (0x95 frames and ATND responses).
_xbee_sxa_debug int _sxa_disc_atnd_response (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Frame handler for processing AT Command Response frames.
_xbee_sxa_debug int _sxa_disc_handle_frame_0x95 (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
Frame handler for processing Node Identification Indicator (0x95) frames.
_xbee_sxa_debug sxa_node_t FAR * sxa_node_by_addr (const addr64 FAR *ieee_be)
_xbee_sxa_debug sxa_node_t FAR * sxa_local_node (const xbee_dev_t *xbee)
_xbee_sxa_debug sxa_node_t FAR * sxa_node_by_name (const char FAR *name)
_xbee_sxa_debug sxa_node_t FAR * sxa_node_by_index (int index)
_xbee_sxa_debug sxa_node_t FAR * sxa_node_add (xbee_dev_t *xbee, const xbee_node_id_t FAR *node_id)
_xbee_sxa_debug void sxa_node_table_dump (void)
_xbee_sxa_debug int _sxa_disc_cluster_handler (const wpan_envelope_t FAR *envelope, void FAR *context)
Cluster handler for `Digi Node Identification` cluster.
_xbee_sxa_debug int _sxa_io_process_response (const addr64 FAR *ieee_be, const void FAR *raw, int length)
Function shared by multiple functions that process I/O sample messages (0x92 frames and ATIS responses).
_xbee_sxa_debug int _sxa_io_response_handler (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
_xbee_sxa_debug int _sxa_io_cluster_handler (const wpan_envelope_t FAR *envelope, void FAR *context)
_xbee_sxa_debug int _sxa_remote_is_cmd_response_handler (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
_xbee_sxa_debug int _sxa_local_is_cmd_response_handler (xbee_dev_t *xbee, const void FAR *raw, uint16_t length, void FAR *context)
_xbee_sxa_debug int sxa_get_digital_input (const sxa_node_t FAR *sxa, uint_fast8_t index)
_xbee_sxa_debug int sxa_get_digital_output (const sxa_node_t FAR *sxa, uint_fast8_t index)
_xbee_sxa_debug int16_t sxa_get_analog_input (const sxa_node_t FAR *sxa, uint_fast8_t index)
_xbee_sxa_debug int sxa_set_digital_output (sxa_node_t FAR *sxa, uint_fast8_t index, enum xbee_io_digital_output_state state)
_xbee_sxa_debug int sxa_io_configure (sxa_node_t FAR *sxa, uint_fast8_t index, enum xbee_io_type type)
_xbee_sxa_debug int sxa_io_set_options (sxa_node_t FAR *sxa, uint16_t sample_rate, uint16_t change_mask)
_xbee_sxa_debug int sxa_io_query (sxa_node_t FAR *sxa)
_xbee_sxa_debug int sxa_io_query_status (sxa_node_t FAR *sxa)
_xbee_sxa_debug void sxa_io_dump (sxa_node_t FAR *sxa)
_xbee_sxa_debug sxa_node_t FAR * sxa_init_or_exit (xbee_dev_t *xbee, const wpan_endpoint_table_entry_t *ep_table, int verbose)
void _sxa_cmd_list_cache_cb (const xbee_cmd_response_t FAR *response, const struct xbee_atcmd_reg_t FAR *reg, void FAR *base)
void _sxa_launch_update (sxa_node_t FAR *sxa, const struct _xbee_reg_descr_t FAR *xrd, uint16_t cache_group)
void sxa_tick (void)
sxa_cache_flags_t sxa_cache_status (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb, uint16_t cache_group)
void _sxa_set_cache_status (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb, uint16_t cache_group, sxa_cache_flags_t flags)
void FAR * sxa_cached_value_ptr (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb)
uint16_t sxa_cached_value_len (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb)
int sxa_find_pending_cache (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb)
int sxa_schedule_update_cache (sxa_node_t FAR *sxa, const _xbee_reg_descr_t FAR *zb)
int sxa_is_digi (const sxa_node_t FAR *sxa)
Variables
XBEE_BEGIN_DECLS typedef uint8_t sxa_cache_flags_t
const char * _xbee_rci_types []
Table to map _xbee_rci_type_t to RCI type string.
const FAR _xbee_reg_descr_t _xbee_reg_table []
sxa_node_t FAR * sxa_table = NULL
int sxa_table_count = 0
sxa_node_t FAR * sxa_local_table = NULL
const FAR xbee_atcmd_reg_t _sxa_ni_query_regs []
const FAR xbee_atcmd_reg_t _sxa_devinfo_query_regs []
const FAR xbee_atcmd_reg_t _sxa_dhdl_query_regs []
const FAR sxa_cached_group_t _sxa_default_cache_groups []
const FAR xbee_atcmd_reg_t _sxa_init_query_regs []
typedef PACKED_STRUCT
Cached generic register value (no data)
sxa_cached_t
uint8_t value
Cached value.
sxa_cached_uint8_t
sxa_cached_uint16_t
sxa_cached_uint32_t
sxa_cached_addr64
const FAR sxa_cached_group_t _sxa_default_cache_groups []
sxa_node_t FAR * sxa_table
int sxa_table_count
sxa_node_t FAR * sxa_local_table
Detailed Description
Macro Definition Documentation
#define _SXA_CACHED_BIN(name, len) PACKED_STRUCT { sxa_cache_flags_t flags; uint8_t value[len]; } name
Cached binary register value.
This is in the form of a macro which generates an in-line struct definition, since binaries are arrays with generally different maximum lengths.
#define _SXA_CACHED_PREFIX_SIZE (sizeof(sxa_cache_flags_t))
Size of cache flags and any other prefix data in each sxa_cached_* struct. Each struct must have same prefix data. Only the final 'value' field may be different.
#define _SXA_CACHED_STRING(name, len) PACKED_STRUCT { sxa_cache_flags_t flags; uint8_t value[len+1]; } name
Cached string register value.
This is in the form of a macro which generates an in-line struct definition, since strings are arrays with generally different maximum lengths.
One extra char is automatically added, for the null terminator.
#define _XRT_ENTRY(state, tag, at, cxv, desc, units, min, max, rci_type, sxa_field, group)
Value:
{ state, #at, cxv, rci_type, \
         offsetof(sxa_node_t,sxa_field), \
         sizeof((*(sxa_node_t *)NULL).sxa_field), \
         SXA_CACHED_##group }
#define SXA_INDEX_TO_IP(index) IPADDR(127,1,0,index)
Macro to generate the appropriate `loopback` IP address, i.e.
the IP address to use to talk to a particular remote node defined by its SXA node table index.
#define SXA_SOCKET_ENDPOINT
Value:
{ \
        WPAN_ENDPOINT_DIGI_STREAM, \
        WPAN_PROFILE_DIGI, \
        _sxa_socket_rx_handler, \
        NULL, \
        0x0000, \
        0x00, \
        NULL }
Place this entry in endpoint table to enable SXA sockets.
#define SXA_SOCKET_MTU 104
Network interface Maximum Transmission Unit, as seen by TCP stack.
Selection of this constant is a bit tricky. ZigBee has a small MTU, however the XBee modules accept larger payloads and fragments them if necessary when transmitting. TCP likes to avoid fragmentation and tries to select an MSS (TCP payload size) as large as possible, but not so large as to require any fragmentation along the transmission path.
There is no reliable method to set the MSS, because the ZigBee MTU depends on various header options such as encryption and source routing. Because of this, we select a conservative value for the TCP MSS of 64 bytes. To this, we add 40 bytes (for the IP and TCP headers) to get an MTU of 104, since TCP computes its MSS by assuming IP and TCP headers are required for each segment. This MTU of 104 exceeds that for ZigBee, however out implementation of SXA sockets effectively compresses the IP and TCP headers into a 6-byte header. This gives a real MTU of 64+6 = 70 bytes. This is an acceptable envelope payload size, which will avoid fragmentation.
Thus, whatever this constant is, the real MTU will be 34 bytes less than this, and the TCP MSS will be 40 bytes less.
#define SXA_STREAM_PORT UINT16_C(61616)
Macro to use for first and last valid TCP port numbers, for both source port and destination port.
This range is selected since port numbers must compress into 8-bit fields.
#define XBEE_DISC_CLIENT_CLUST_ENTRY
Value:
{ DIGI_CLUST_NODEID_MESSAGE, _sxa_disc_cluster_handler
      , NULL, \
      WPAN_CLUST_FLAG_INPUT | WPAN_CLUST_FLAG_NOT_ZCL }
#define XBEE_FRAME_HANDLE_IS_RESPONSE
Value:
{ XBEE_FRAME_REMOTE_AT_RESPONSE, 0,
      _sxa_remote_is_cmd_response_handler, NULL }, \
   { XBEE_FRAME_LOCAL_AT_RESPONSE, 0,
      _sxa_local_is_cmd_response_handler, NULL }, \
   { XBEE_FRAME_IO_RESPONSE, 0, _sxa_io_response_handler,
       NULL }
Macro for registering a handler to receive I/O samples via both ATIS responses and 0x92 frames received.
Note that the XBEE_FRAME_IO_RESPONSE (0x92) handler is only necessary when ATAO=0. When ATAO is not zero, the 0x92 frames come in as 0x91 frames on the Digi Data Endpoint.
#define XBEE_FRAME_HANDLE_ND_RESPONSE
Value:
{ XBEE_FRAME_LOCAL_AT_RESPONSE, 0,
      _sxa_disc_atnd_response, NULL }, \
      { XBEE_FRAME_NODE_ID, 0, _sxa_disc_handle_frame_0x95
      , NULL }
Macro for registering a handler to receive node announcements via both ATND responses and 0x95 frames received.
Note that the XBEE_FRAME_NODE_ID (0x95) handler is only necessary when ATAO=0. When ATAO is not zero, the 0x95 frames come in as 0x91 frames on the Digi Data Endpoint.
#define XBEE_IO_CLIENT_CLUST_ENTRY
Value:
{DIGI_CLUST_IODATA, _sxa_io_cluster_handler, NULL, \
         WPAN_CLUST_FLAG_INPUT | WPAN_CLUST_FLAG_NOT_ZCL
      }
Typedef Documentation
typedef void(* sxa_cache_upd_fn)(struct sxa_node_t FAR *sxa, const struct sxa_cached_group_t FAR *cgroup)
Function registered for cache group update post-processing.
Parameters
in sxa Relevant SXA.
in cgroup Cache group being updated (within sxa)
Enumeration Type Documentation
anonymous enum
Enumerator:
_SXA_CACHED_UNKNOWN
 Cached register value status: value unknown (never read)
_SXA_CACHED_OK
 Cached register value status: value read successfully from device
_SXA_CACHED_ERROR
 Cached register value status: value could not be read from device
_SXA_CACHED_BUSY
 Cached register value status: value is being read from device
_SXA_CACHED_PENDING
 Cached register value status: value is pending a radio query
_SXA_CACHED_BAD_GROUP
 Cached register value status: not a valid cache group
anonymous enum
This enum gives numeric identification to all cache groups.
Enumerator:
SXA_CACHED_NONE
 Dummy for when no caching required.
SXA_CACHED_NODE_ID
 Got .id.node_id (normally obtained by initial discovery, however app can explicitly refresh if desired).
SXA_CACHED_IO_CONFIG
 I/O configuration: ATD0 etc., in .io field.
SXA_CACHED_DEVICE_INFO
 Device information: HV, VR and DD.
SXA_CACHED_DHDL
 Dest addr: DH,DL. This is a group since it is exceptional in requiring two commands to get a single (logical) 64 bit value.
SXA_CACHED_MISC
 Miscellaneous stuff (one of the sxa_cached_* sub-structures) - these have their own individual cache status flags. This should be the last entry, and not have an entry in the group table. Miscellaneous entries have their cache status flag immediately before the binary data, and thus do not need a group table entry.
Function Documentation
int _sxa_disc_atnd_response (xbee_dev_t * xbee, const void FAR * raw, uint16_t length, void FAR * context)
Frame handler for processing AT Command Response frames.
Should only be called by the frame dispatcher and unit tests.
See the function help for xbee_frame_handler_fn() for full documentation on this function's API.
References _sxa_disc_process_node_data(), FAR, value, and XBEE_AT_RESP_STATUS.
int _sxa_disc_cluster_handler (const wpan_envelope_t FAR * envelope, void FAR * context)
Cluster handler for `Digi Node Identification` cluster.
Used in the cluster table of WPAN_ENDPOINT_DIGI_DATA (0xE8) for cluster DIGI_CLUST_NODEID_MESSAGE (0x0095).
Parameters
in envelope information about the frame (addresses, endpoint, profile, cluster, etc.)
in,out context
Return values
0 handled data
!0 some sort of error processing data
See Also
wpan_aps_handler_fn()
References _sxa_disc_process_node_data().
int _sxa_disc_handle_frame_0x95 (xbee_dev_t * xbee, const void FAR * raw, uint16_t length, void FAR * context)
Frame handler for processing Node Identification Indicator (0x95) frames.
Should only be called by the frame dispatcher and unit tests.
See the function help for xbee_frame_handler_fn() for full documentation on this function's API.
References _sxa_disc_process_node_data(), FAR, and node_data.
int _sxa_disc_process_node_data (xbee_dev_t * xbee, const void FAR * raw, int length)
Function shared by multiple functions that process Node Identification Messages (0x95 frames and ATND responses).
Parameters
in xbee device that received the message
in raw pointer to the message
in length length of the message
Return values
0 successfully parsed
!0 error parsing data or calling handler()
References EINVAL, FAR, hex_dump(), HEX_DUMP_FLAG_OFFSET, and xbee_disc_nd_parse().
Referenced by _sxa_disc_atnd_response(), _sxa_disc_cluster_handler(), and _sxa_disc_handle_frame_0x95().
int _sxa_io_process_response (const addr64 FAR * ieee_be, const void FAR * raw, int length)
Function shared by multiple functions that process I/O sample messages (0x92 frames and ATIS responses).
Parameters
in xbee device that received the message
in raw pointer to the message (starting at sample count field)
in length length of the message
Return values
0 successfully parsed
!0 error parsing data
References EINVAL, FAR, hex_dump(), HEX_DUMP_FLAG_OFFSET, xbee_io_response_dump(), and xbee_io_response_parse().
Variable Documentation
const FAR sxa_cached_group_t _sxa_default_cache_groups[]
Initial value:
=
{
   _SXA_CG_INIT(SXA_CACHED_NODE_ID, node_id_cf,
      _sxa_ni_query_regs, NULL),
   _SXA_CG_INIT(SXA_CACHED_IO_CONFIG, io_config_cf,
      NULL, _sxa_update_io_config_group),
   _SXA_CG_INIT(SXA_CACHED_DEVICE_INFO,device_info_cf,
      _sxa_devinfo_query_regs, NULL),
   _SXA_CG_INIT(SXA_CACHED_DHDL, dhdl_cf,
      _sxa_dhdl_query_regs, NULL),
   _SXA_CG_INIT_END
}
const FAR xbee_atcmd_reg_t _sxa_devinfo_query_regs[]
Initial value:
= {
   XBEE_ATCMD_REG_MOVE_THEN_CB('A', 'O',
      XBEE_CLT_COPY_BE,
                  sxa_node_t, ao,
                  _sxa_process_version_info, 0),
   XBEE_ATCMD_REG('H', 'V', XBEE_CLT_COPY_BE,
      sxa_node_t, hardware_version),
   XBEE_ATCMD_REG_MOVE_THEN_CB('V', 'R',
      XBEE_CLT_COPY_BE,
                  sxa_node_t, firmware_version,
                  _sxa_process_version_info, 1),
   XBEE_ATCMD_REG('D', 'D', XBEE_CLT_COPY_BE,
      sxa_node_t, dd),
   XBEE_ATCMD_REG_END
}
const FAR xbee_atcmd_reg_t _sxa_dhdl_query_regs[]
Initial value:
= {
   XBEE_ATCMD_REG('D', 'H', XBEE_CLT_COPY,
      sxa_node_t, dest_addr.l[0]),
   XBEE_ATCMD_REG('D', 'L', XBEE_CLT_COPY,
      sxa_node_t, dest_addr.l[1]),
   XBEE_ATCMD_REG_END
}
const FAR xbee_atcmd_reg_t _sxa_init_query_regs[]
Initial value:
= {
   
   XBEE_ATCMD_REG_SET_8('N', 'O', 2),
}
const FAR xbee_atcmd_reg_t _sxa_ni_query_regs[]
Initial value:
= {
   XBEE_ATCMD_REG('N', 'I', XBEE_CLT_COPY,
      sxa_node_t, id.node_info),
   XBEE_ATCMD_REG_END
}
const char* _xbee_rci_types[]
Initial value:
=
{
   
   "uint32",
   "0x_hex32",
   "string",
   "string",
   "xbee_ext_addr",
}
Table to map _xbee_rci_type_t to RCI type string.
typedef PACKED_STRUCT
Initial value:
{
   sxa_cache_flags_t flags
Cached generic register value (no data)
Cached extended address register value.
Cached uint32_t register value.
Cached uint16_t register value.
Cached uint8_t register value.
Cache status flags (_SXA_CACHED_OK etc.)
Referenced by _zcl_discover_attributes(), _zcl_read_attributes(), _zcl_send_read_from_zdo_match(), _zcl_write_attributes(), _zdo_active_ep_respond(), _zdo_match_desc_respond(), _zdo_process_ieee_addr_resp(), _zdo_process_nwk_addr_resp(), _zdo_simple_desc_respond(), xbee_cmd_simple(), xbee_frame_write(), zcl_client_read_attributes(), zcl_comm_reset_parameters(), zcl_comm_response(), zcl_comm_restart_device(), zcl_default_response(), zcl_identify_command(), zcl_send_write_attributes(), zdo_match_desc_request(), zdo_mgmt_leave_req(), zdo_send_bind_req(), and zdo_send_descriptor_req().
XBEE_BEGIN_DECLS typedef uint8_t sxa_cache_flags_t
\internal Flag data for register value cache status
For this library to work, structure packing must be enabled (accomplished using the PACKED_STRUCT macro). This is because the size of the actual data must be derivable from the size of the containing structure, minus the size of the following flags field.
The flags field takes on one of the _SXA_CACHED_OK etc. values.